inst/templates/CONDUCT.md
Like hadley/devtools#840 but for the other copy of CONDUCT.md (Originally submitted as hadley/devtools#1515)
=> Added forward slashes to URL in CONDUCT.md

R/create.R
=> Normalize the path before calling utils::browseURL

DESCRIPTION, R/package.R, R/tidyverse.R, README.Rmd, README.md, man/tidyverse.Rd, man/use_package.Rd
I noticed the `simulated` typo in the README and figured I'd run `devtools::spell_check()` over the rest, which caught a few more. 
`callr` was added to `DESCRIPTION` but this may be unnecessary.
=> Minor typos

R/description.R, man/create_package.Rd, man/use_description.Rd
=> Remove stray sentence fragment

R/r.R
=> Allow numbers in the name of .R files

R/pkgdown.R
I believe the correct directory is docs/ -- not doc/. Closes PR #167.
=> In use_pkgdown() replace doc by docs

R/helpers.R
This seems more natural to me and it makes more functions more testable.
I have run tests locally in my [testing branch](https://github.com/r-lib/usethis/tree/add-tests) with this commit and everything still passes.
=> Create file even if can't open for immediate edit

R/github-labels.R
in `use_github_labels()`. Yellow, like in dplyr.
=> Add performance label

R/create.R, man/create_from_github.Rd, man/create_package.Rd
Fixes #129 Figure out how to switch projects on RStudio server
=> Prefer rstudioapi::openProject() because RStudio server

NEWS.md, R/create.R, tests/testthat/test-create.R
Fixes #227
This whole situation might improve once we switch to fs (#177).
=> Re-normalize path, after it is guaranteed to exist

inst/templates/SUPPORT.md
=> Fix minor typo

inst/templates/tidy_contributing.md
=> Clarify placement of bullet in NEWS

R/helpers.R, tests/testthat/test-use-dependency.R
Fixes #99 `use_dependency()` should check for existing imports
=> Consult existing dependencies in use_dependency()

inst/templates/tidy_contributing.md
* Describes editing documentation from GitHub
* Adds period to end of NEWS bullet template
* PR process header now in sentence case
=> Add "Fixing typos" section to contributing

R/proj.R, R/usethis-package.R
=> Refactor proj_get() and proj_set()

vignettes/articles/usethis-setup.Rmd
* Change "and or" to "and/or".
* Add link to devtools at first mention.
* Add link to nano editor.
* Swap order to use "GitHub repository".
* Prefix `create_from_github()` with `usethis::`.
* Bold Mac and Windows for ease of reading.
[_Feel free to just implement select ones (or none) at will, and I'll close the PR._]
=> Make minor edits to usethis-setup article.

R/tidyverse.R
=> Style `use_tidy_style()`.

R/tidyverse.R
=> Put strict on its own line for tidy style.

DESCRIPTION, R/github.R, man/use_github.Rd
=> Use git2r::repository_head() and depend on dev git2r

.github/CODEOWNERS
* Add CODEOWNERS w/ @hadley as principal, @jennybc as understudy.
=> Add codeowners w/ understudy

R/tidyverse.R
=> Format `use_tidy_thanks()` for markdown

R/description.R, R/tidyverse.R, man/use_description.Rd, tests/testthat/test-use-description.R
Fixes #396 Ensure default DESCRIPTION matches use_tidy_description()
=> Tidy default description

R/package.R
Fixes #200 use_dev_package should always set package version
=> Set a minimum version in use_dev_package()

R/badge.R, R/ci.R
A couple of minor tweaks that should make badges slightly more useful for visually impaired readers
=> Improve alt text for badges

inst/templates/tidy-travis.yml
=> Use build matrix in tidy-travis.yml

R/pr.R, man/pr_init.Rd
=> Minimum needed to fetch PR for a repo you don't own

R/pr.R, man/pr_init.Rd
Related to #534 
`pr_finish` was exported but not in the documentation
=> add exported pr_finish to documentation

NEWS.md, R/vignette.R, tests/testthat/test-vignette.R
=> Use vignette filenames

R/proj.R, R/ui.R
* Use base = NA to not relativise path
* Also need path_expand() in proj_rel_path()
Fixes #538
=> Improve ui_path styling

R/pkgdown.R
=> Improvements to use_pkgdown_travis

R/git-utils.R
Fixes #592 Relax check for uncommitted changes?
=> Don't worry about files that are uncommitted AND untracked, by default

vignettes/articles/usethis-setup.Rmd
Warning: This PR fixes the source but does not re-build the site.
=> Reflect that pkgbuild is now on CRAN

_pkgdown.yml
Add git_sitrep() and git_vaccinate() to pkgdown function-reference
=> Add git utilities to function-reference, fix #650

vignettes/articles/usethis-setup.Rmd
Fix #668 
Ready-to-go from my perspective, but happy to make any changes you may propose
=> Include git_sitrep() in setup article

R/git-utils.R, R/git.R, R/github-utils.R, R/pr.R
Consider this Act One in providing better support for collaborative workflows.
Other than some possible minor UI tweaks, it's all we're likely to do in this release. We'll do more when we tackle "unbork my fork" (#618).
=> Add more info to git_sitrep()

NEWS.md, R/create.R, man/create_from_github.Rd
Fixes #695
- includes NEWS item and amended documentation
=> Make create_from_github() work for an existing fork

NEWS.md, R/data.R, inst/templates/packagename-data-prep.R, man/use_data.Rd, tests/testthat/test-use-data.R
=> Accept dataset name in use_data_raw(); template the data prep script

DESCRIPTION
=> Update glue version to >= 1.3.0

R/github-labels.R, R/github.R, man/use_github_labels.Rd
This is a gross monster function but it's doing what we want. I just applied it on a rather massive scale across most of tidyverse and r-lib.
=> Unbork GitHub labels

R/badge.R, man/badges.Rd, tests/testthat/test-use-badge.R
- Require GitHub
- Add support for `urlpath` component
=> use_binder_badge() tweaks

R/roxygen.R, man/use_roxygen_md.Rd
=> Fix wording of use_roxygen_md()

README.Rmd, README.md, tests/testthat/test-use-pkgdown.R
I'm also trying to sort out #764 by making a PR as myself, from a different machine
=> pkgdown is only Suggested, so be prepared to skip

R/git.R, man/git_sitrep.Rd
Improves documentation to explain what does it mean to be Vaccinated in this sitrep.
I haven't redocumented the man folder so I expect this to fail on travis
=> Improve documentation of git_sitrep

NEWS.md, R/rmarkdown.R, man/use_rmarkdown_template.Rd
=> Remove unexported function from use_rmarkdown_template signature

R/pkgdown.R, man/use_pkgdown.Rd
Closes #872 
I also expanded upon the documentation about what exactly `use_pkgdown_travis()` does, but I don't know how much detail you usually document these functions with so I can remove that if you want.
=> Inform that a gh-pages branch is created in use_pkgdown_travis()

NEWS.md, R/proj.R, R/r.R
=> Make get_active_r_file() more robust to `~/` issues on Windows

.github/CONTRIBUTING.md, inst/templates/tidy-contributing.md
_n.b._ I made the changes directly to the template, and held off on re-generating the usethis-specific contributing guide.
=> Edit updated contributing template.

R/data.R, man/use_data.Rd
Closes #801 (I assume it's ok to close this despite the fact that it's not addressing the "future" part of this discussion). 
I kept the message as brief as possible with a link to [the data chapter](https://r-pkgs.org/data.html), but let me know if there should be a bit more guidance.
=> Remind user to document exported data

R/pr.R, man/pr_init.Rd
=> link PR vignette from PR helpers manual page

R/description.R, man/use_description.Rd
=> Describe using non-package DESCRIPTION files in `use_description()` docs

R/github-action.R, R/github-actions.R, man/github_actions.Rd, man/use_github_action.Rd
Regression introduced in #998.
=> Reorganize gh-actions docs

R/tidyverse.R
=> Add period to end of use_tidy_thanks() output

inst/templates/codecov.yml
=> Don't fail if codecov drops

R/helpers.R, R/lifecycle.R, man/proj_utils.Rd, tests/testthat/test-lifecycle.R
* Don't display default package usage hints
* Don't normalize description
Fixes #1012
=> Tweak use_lifecycle()

DESCRIPTION, R/github.R, R/utils.R, tests/testthat/helper.R
=> Check that the internet is on

inst/templates/tidy-contributing.md
This vignette was recently renamed
=> Fix broken url in CONTRIBUTING template

NEWS.md, R/course.R, man/use_course_details.Rd, man/zip-utils.Rd, tests/testthat/test-use-course.R
=> Equip tidy_download() with retries (with a longer connect timeout)

NEWS.md, R/create.R, R/tidyverse.R, cran-comments.md, man/create_package.Rd, man/tidyverse.Rd
=> More updates for create_tidy_package()

R/code-of-conduct.R, R/logo.R, R/pkgdown.R, R/proj.R, R/release.R, man/edit_file.Rd, man/use_code_of_conduct.Rd, tests/testthat/test-pkgdown.R
I looked into the pkgdown helpers, reflecting on some recent pre-release checks in usethis and devtools.
And discovered @Hadley, @jimhester, and I had all added various pieces of redundant and partially implemented functionality. So I cleaned it up.
The review request and tagging is as much about raising awareness than anything else.
=> Pkgdown cleanup

R/git.R, R/pr.R, R/utils-github.R
Makes calls to gert robust against parameter re-ordering.
=> Use named arguments for gert

NEWS.md, R/test.R, man/use_testthat.Rd, tests/testthat/test-test.R
=> Set edition in use_testthat()

DESCRIPTION, R/cpp11.R, inst/templates/code-cpp11.cpp, tests/testthat/test-cpp11.R
=> Sync usethis with current cpp11 conventions

R/test.R, man/use_testthat.Rd, tests/testthat/test-test.R
* Better edition detection
* Always override existing values
* Make it easy to turn on parallel testing
* Error if try to set edition outside of package
=> Improve use_testthat()

R/proj.R, man/proj_utils.Rd, tests/testthat/test-proj.R
=> Also change working directory for temporary projects

R/github-labels.R
This will fix #1284 
Tested and it works now.
=> Fix renaming of existing issue

R/github_token.R
applies some straightforward fixes:
- surrounds host name with quotes
- adapts argument names to functions
=> tweak gh_token_help() for GHE

R/create.R, R/github_token.R, tests/testthat/test-github_token.R
fix #1294 
Given this is a more-substantial change than the previous PR's, I am mindful that I might not have put things in the "right place".
=> reworking host_hint and code_hint

R/rstudio.R
=> Adjust rappdirs call for Windows

inst/templates/pipe.R
=> use_pipe() now documents arguments and return value

R/release.R, tests/testthat/_snaps/release.md
=> Don't prompt to update CRAN-comments on first release

NEWS.md, R/lifecycle.R, man/use_lifecycle.Rd, tests/testthat/_snaps/lifecycle.md, tests/testthat/test-lifecycle.R
Fixes #1419
Any suggestions for tests?
=> Import lifecycle::deprecated() in use_lifecycle()

DESCRIPTION
=> add MB to authors

DESCRIPTION, NEWS.md
A minimal PR to help with #1450 - I don't know if this merits a NEWS item; I'll be happy to add one if you think it does.
=> update minimum version of gh

inst/templates/tidy-contributing.md
dependences to dependencies line 23
=> dependences to dependencies line 23

R/pkgdown.R, man/use_pkgdown.Rd
Technically "that" or "which" would also fit here.
=> Fixed use_pkgdown documentation typo.

DESCRIPTION, NEWS.md, R/edit.R, R/git.R, R/utils-git.R, man/edit.Rd, man/git_vaccinate.Rd
=> Be more careful to consult/manage core.excludesFile

R/release.R, tests/testthat/_snaps/release.md
Since it's now on CRAN (and the link makes it harder to copy and paste into R)
=> Drop link to urlchecker

NEWS.md, R/code-of-conduct.R, R/logo.R, R/pkgdown.R, tests/testthat/test-pkgdown.R
=> Only remove trailing slashes in `tidyverse_url()`

NEWS.md, R/github-actions.R, R/use_github_file.R, man/github_actions.Rd, man/use_github_file.Rd
We need to put a little thought into a better solution. At a minimum, version should probably become a parameter.
=> Quick hack to use latest actions

R/release.R, tests/testthat/_snaps/release.md
=> Update RStudio internal comms instructions

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/test-coverage.yaml, NEWS.md, R/github-actions.R, man/github_actions.Rd, man/tidyverse.Rd, tests/testthat/_snaps/github-actions.md, tests/testthat/test-github-actions.R
=> Consult ref for GHA workflows

R/github-actions.R
=> gluify string

R/tidy-upkeep.R, tests/testthat/_snaps/tidy-upkeep.md
Updating tidy_upkeep checklist for 2022
=> Add upkeep bullets for 2022

R/release.R
=> Look for the package-under-development by name

inst/templates/testthat.R
=> Add advice to do test config somewhere other than tests/testhat.R

tests/testthat/test-ci.R, tests/testthat/test-course.R, tests/testthat/test-cpp11.R, tests/testthat/test-create.R, tests/testthat/test-data-table.R, tests/testthat/test-description.R, tests/testthat/test-git-default-branch.R, tests/testthat/test-github-actions.R, tests/testthat/test-package.R, tests/testthat/test-pkgdown.R, tests/testthat/test-proj.R, tests/testthat/test-rcpp.R, tests/testthat/test-readme.R, tests/testthat/test-roxygen.R, tests/testthat/test-tibble.R, tests/testthat/test-tidyverse.R, tests/testthat/test-tutorial.R, tests/testthat/test-utils-github.R
=> use brackets with mockr

NEWS.md, R/create.R, R/rstudio.R, inst/templates/template.Rproj, man/use_rstudio.Rd, tests/testthat/test-rstudio.R
And set to `FALSE` in `create_from_github()`. Fixes #1679
=> Add reformat argument to `use_rstudio()`

NEWS.md, tests/testthat/_snaps/use_import_from.md
=> update snapshot test

NEWS.md, R/utils-git.R
Fixes #1718
There may be a cleaner way to get this done; I think this makes a small change, which I hope will also be clear in intent.
=> refactor `git_cfg_get()`

vignettes/articles/git-credentials.Rmd
Given recent events maybe it is worth removing ~lastpass~?
=> Consider removing the lastpass mention

DESCRIPTION, tests/testthat/helper.R, tests/testthat/test-badge.R, tests/testthat/test-course.R, tests/testthat/test-create.R, tests/testthat/test-directory.R, tests/testthat/test-edit.R, tests/testthat/test-git.R, tests/testthat/test-logo.R, tests/testthat/test-proj.R, tests/testthat/test-roxygen.R, tests/testthat/test-template.R, tests/testthat/test-utils-git.R, tests/testthat/test-utils-github.R, tests/testthat/test-write.R
Test driving https://github.com/r-lib/testthat/pull/1690
=> Switch to expect_without_error()

NEWS.md, R/r.R, man/rename_files.Rd, tests/testthat/_snaps/r.md, tests/testthat/test-r.R
=> Also rename files in src/

R/github-labels.R, man/use_github_labels.Rd
Fixes #1727
@jennybc hopefully nothing too surprising here
=> Improve use_tidy_github_label() docs

R/create.R
=> Add some post-fork, pre-clone sleep

R/tidyverse.R
Updating CoC email address for tidyverse.
=> Updating CoC email address

R/release.R, R/version.R, tests/testthat/_snaps/version.md, tests/testthat/test-version.R
=> Omit dev version from choices in use_release_issue()

R/release.R, R/tidy-upkeep.R, tests/testthat/_snaps/tidy-upkeep.md
Change `pak::pkg_install()` to `pak::pak()` and be a bit more strict on detecting rstudio email addresses
=> Upkeep tweaks

R/tidy-upkeep.R, tests/testthat/_snaps/tidy-upkeep.md, tests/testthat/test-tidy-upkeep.R
A bit late in the week, but still worth it, I think.
=> Remind to re-`document()`

R/proj.R, man/proj_utils.Rd
Closes #1795 
Alternatively, we might just re-use this snippet:
https://github.com/r-lib/usethis/blob/654a96576bca12f33aa81cab98fb19b4d0db1f1b/R/proj.R#L221-L222
=> Attempt to bubble up failure message from rprojroot::find_root

R/git.R
=> Add .quarto to standard .gitignore

NEWS.md, R/namespace.R, R/news.R, R/package.R, R/r.R, R/readme.R, R/release.R, R/test.R, R/version.R, inst/templates/testthat.R, man/use_namespace.Rd, man/use_news_md.Rd, man/use_package.Rd, man/use_r.Rd, man/use_readme_rmd.Rd, man/use_testthat.Rd, man/use_version.Rd, tests/testthat/_snaps/release.md
Closes #1689, but I also went through and checked all of the links and changed those that were dead or redirected.
=> Fix links to R Packages book 2e

R/upkeep.R, tests/testthat/_snaps/upkeep.md
* use_tidy_description()
* Explain use_github_action() usage
=> Add some upkeep bullets

vignettes/articles/git-credentials.Rmd
There were a couple of left over references to LastPass after PR #1725 which I have replaced with Bitwarden. Happy to just remove references to LP if you prefer.
=> Replace references to Lastpass with Bitwarden

R/documentation.R, man/use_package_doc.Rd
revert part of #1898 due to roxygen2 7.3.0 fixing this.  https://github.com/r-lib/roxygen2/pull/1535
=> remove note about package docs problems

NEWS.md, inst/templates/package-README, tests/testthat/_snaps/readme.md, vignettes/articles/usethis-setup.Rmd
=> Mention pak instead of devtools in README template

R/utils-git.R
just a small typo from #1949.
Currently getting a double argument error.
This PR is useless if #1978 gets merged first as I included the change there as I was trying to resolve conflicts
=> Fix `pr_merge_main()`

R/pr.R
don't know if this will work, but will test after merged
closes #1992
=> Tickle git pane with `pr_finish()`

R/github-labels.R
=> Remove link from tidy-dev-day github issues label

R/pipe.R, man/use_pipe.Rd
=> Fix wording

R/course.R, man/zip-utils.Rd
Add pos.it to the vector of acceptable shortlinks for the `use_course` function (Fixes #1942)
=> Add pos.it to acceptable shortlinks for use_course

DESCRIPTION, NEWS.md, R/release.R, tests/testthat/_snaps/release.md, tests/testthat/test-release.R
=> Only print revdep checklist items if revdeps exist for the current package

R/upkeep.R
Fixes
```
Error in `tidy_upkeep_checklist()`:
! object 'desc' not found
```
=> Fix 2024 upkeep list

R/author.R, R/description.R, README.Rmd, README.md, man/use_author.Rd, tests/testthat/_snaps/author.md, tests/testthat/test-author.R
=> Omit ORCID placeholder from defaults

R/data.R, R/release.R, R/upkeep.R, tests/testthat/test-data.R
=> Never lower an R version requirement in `use_data()`

R/roxygen.R, tests/testthat/test-roxygen.R
=> Make 'markdown = TRUE' check less brittle

R/release.R, R/upkeep.R, tests/testthat/_snaps/upkeep.md
=> Add 2025 bullets for tidy upkeep

NEWS.md, R/helpers.R, R/package.R
plus some internal renaming.
Fixes https://github.com/r-lib/usethis/issues/2118
=> fix: properly handle `use_package(min_version = FALSE)`

R/pkgdown.R, R/upkeep.R
Closes #1922 
Bullet placed looks like this:
=> Nudge people towards Bootstrap 5

NEWS.md, R/course.R, man/zip-utils.Rd
=> Assume the folder from use_course() should be treated as a project

DESCRIPTION, R/create.R, tests/testthat/test-create.R
=> Account for the absence of Quarto CLI
