r-lib/usethis

R/github.R

The first call to `use_description_field` does not pass the `base_path` argument on.

Pass base path to both use_description_field calls

---

R/ci.R

because shields.io seems to lead to R CMD check problems.

Use native codecov badge

---

DESCRIPTION
NEWS.md
R/style.R

This makes it easy to paste into the source files where needed.
It looks like all current uses of `code_block()` are places where it makes sense to put the code on the clipboard. If we think this may change in the future we could either have an option to `code_block()`, or have a helper function which calls `clipr::write_clip()` and `code_block()` internally and switch the current uses of `code_block()` to the helper.
Fixes #52

Use clipr to add code to clipboard

---

R/cran.R
R/news.R
R/readme.R
R/test.R
man/use_cran_comments.Rd
man/use_news_md.Rd
man/use_readme_rmd.Rd
man/use_testthat.Rd

As per issue #86. Some infrastructure-creation functions automatically open the resulting files in the current session, which is not always the desired behaviour. This is because these functions wrap `use_template()` with a hard-coded `open = TRUE` argument.
In this branch, I added `open = TRUE` arguments to the relevant wrapper functions, and replaced the hardcoded `open = TRUE` in the body of the functions with `open = open`.
The more recent commit is writing some automated tests to ensure these functions still execute without error.

Chooseopen: passing "open = T/F" arguments to use_template()

---

inst/templates/tidy-eval.R

Addresses #98
Added the syntactic-sugar versions, too - please let me know if they should not be there.
Also, seemed to be more than six functions there, so thought I would remove the count.
If you think it would be constructive to export these, I can amend to add
```
#' @export UQ UQS !! !!!
```
as well as a sentence to the descriptive paragraph.

adds import of UQ, UQS, !!, and !!!

---

inst/templates/omni-README

Meant to combat figs that run off the page for README.html that CRAN creates and hosts.
Suggests the use of, e.g.,
```{r echo = FALSE}
knitr::include_graphics("man/figures/i-already-exist.png")
```
for pre-made figs.

Set an explicit default width of 100% for README figs

---

R/revdep.R

See https://github.com/r-lib/revdepcheck/issues/77
for details.

revdep: git ignore .noindex files, used on macOS

---

inst/templates/omni-README

Fix use_readme_rmd() to exclude comma after last argument passed to knitr::ops_chunk$set (#112)

Remove comma after last argument passed to knitr::ops_chunk$set

---

tests/testthat/test-git.R
tests/testthat/test-use_readme.R

The copious use of `cat()` in usethis makes tests prone to chattiness.
I can silence some tests by switching over to `scoped_temporary_package()`.
`scoped_temporary_package()` uses `utils::capture.output()` to absorb output.
If I need to capture output for the sake of silence (vs. testing the output), should I also use `utils::capture.output()` or `testthat::capture_output()`?

Silence tests

---

DESCRIPTION
R/description.R
R/helpers.R
R/write.R
tests/testthat/test-use_readme.R
tests/testthat/test-write.R

Fixes #148 Reconsider comparison method in `same_contents()`
Fixes `same_contents()` and `write_over()` on Windows, by keeping proposed text as a character vector. This avoids OS-specific line ending issues when deciding if proposed text is same as current. With this, all tests now pass on Windows.

Windows-proof same_contents()

---

R/create.R
R/proj.R

Fixes #154 Make sure all new projects meet one project criterion
Also added `is_proj()`. These are little odds and ends that look helpful as I write a bunch of tests, which will come in a separate PR.

Set .here for projects that don't meet other criteria

---

R/helpers.R

Fixes #157 use_description_field() isn't done yet

Handle new value for existing DESCRIPTION field when `overwrite = FALSE`

---

R/data.R
man/use_data.Rd

Fixes #158 Should `use_data()` check if project is a package? 
We decided that YES it should check and it should refuse to operate on a non-package project at this point.
This is tested in #156, which is still developing.

Restrict use_data() to packages

---

DESCRIPTION
R/create.R
R/github.R
R/readme.R
R/rstudio.R
R/utils.R
man/use_readme_rmd.Rd
tests/testthat/helper.R
tests/testthat/test-use_readme.R

Fixes #142 (Think about behaviour of `yesno()` inside tests), where by "think about" I actually meant "make less annoying".
You also touched on this here (https://github.com/r-lib/usethis/issues/111#issuecomment-353196290), though I am not throwing an error. I'm just assuming the user has NOT authorized whatever action was being proposed. It feels like an error would be a net negative from the testing point of view.
I find `nope()` makes it a bit easier to remember that `TRUE` means "no" and `FALSE` means "yes".
The [branch where I'm accumulating tests](https://github.com/r-lib/usethis/tree/add-tests) passes with this.

Rename yesno() to nope(); use our own interactive()

---

R/badge.R
R/data.R
R/description.R
R/dev-version.R
R/documentation.R
R/helpers.R
R/namespace.R
R/package.R
R/proj.R
R/revdep.R
R/test.R
R/vignette.R
tests/testthat/test-proj.R

I decided to delegate the definition of a package to rprojroot.
I think every function I applied `check_is_package()` to is a no-brainer. We will soon find out if it's annoying that any of these refuse to work on non-package projects.
There are probably more functions that should call `check_is_package()`, but this still represents progress.

Add is_package() and check_is_package()

---

R/edit.R
R/helpers.R
tests/testthat/helper.R
tests/testthat/test-edit.R

Fixes #183 Location of user-level git dotfiles on Windows
Two themes, all inspired by vetting `edit_*()` functions:
* Make sure parent directory/ies exists for anything we attempt to `edit_*()`
* Account for different default location of user-level git dot files on Windows vs. *nix
All triggered by empirical failures on Travis, AppVeyor and local Windows VM.
*In general, I'm accumulating tests in [this branch/PR](https://github.com/r-lib/usethis/pull/156), prioritized by the number of untested lines, and making small changes in master as I go. But this is a bit bigger.*

Make edit_*() functions more tolerant of Windows + naive systems

---

R/course.R
R/rstudio.R

Fixes #202 browseURL() on RStudio Server

Don't try to browse local folder on RStudio server

---

R/create.R
R/proj.R
man/create_from_github.Rd

Fixes #114. For now. In some sense.
Basically this function currently only supports cloning from a public repo. If a PAT is detected, then forking is possible. To make it do more .... will require more time than we have for this release. It needs to have a lot of the same functionality as `use_github()`, but going in the opposite direction (#215 `create_from_github()` should share many arguments with `use_github()`). I've also created a more general issue for GitHub connectivity #214.

Progress on create_from_github()

---

R/course.R
man/use_course.Rd
man/use_course_details.Rd
tests/manual/manual-use-course.R
tests/testthat/test-use-course.R

Prepend https:// to url in use_course()

---

R/description.R

Currently the default field is not title case, so if you check a newly created package with `--as-cran` you get a NOTE.
The Title field should be in title case, current version then in title case:
‘What the Package Does (one line, title case)’
‘What the Package Does (One Line, Title Case)’
Maybe the note is helpful in that it reminds you to change the title, but maybe not and it would be nicer to avoid the note.

Make the default Title title case

---

NEWS.md
R/ci.R

Previously the appveyor badge was not properly rendered as appveyor_info returned the url of the repository as the image. The change only affects the name of the urls returned by appveyor_info to be used by use_badge_appveyor.

Return the correct urls from appveyor

---

NEWS.md
R/badge.R

I changed the URL for the CRAN badge image to use HTTPS. The HTTP URL caused my pkgdown site hosted on GitHub Pages to be labeled as insecure (https://github.com/jdblischak/workflowr/issues/96).
The HTTPS URL appears to work, e.g. here is the badge for usethis using HTTPS: [![CRAN status](https://www.r-pkg.org/badges/version/usethis)](https://cran.r-project.org/package=usethis)

Use HTTPS for CRAN badge image.

---

R/create.R
R/github.R
R/utils.R
man/create_from_github.Rd
man/use_github.Rd
man/use_github_labels.Rd
tests/manual/manual-create-from-github.R
tests/testthat/test-create.R

Fixes  #215 `create_from_github()` should share many arguments with `use_github()`
Fixes #214 GitHub connectivity
I think this completes the obvious set of GitHub operations a typical user would expect. At least in terms of project initiation.
* Clones from the ssh or https url (vs the git url, previously), which stores a usable URL for the `origin` remote, i.e. pull/push should now work going forward
* More explicit logic re: forking and PAT availability
* Adds `upstream` remote in case of fork, also honouring ssh vs https protocol
* Allows token, credentials, host to be specified

Better create_from_github()

---

R/create.R
R/rstudio.R
tests/testthat/helper.R
tests/testthat/test-browse.R
tests/testthat/test-create.R

I suffer from this frequently when other activities have left a stray `.Rproj` file in the session temp directory. ~~Is this kosher? No one should be putting anything of value there, right?~~

Tolerate .Rproj files in the session temp dir

---

R/course.R
man/use_course.Rd

Fixes #238 Automatically open a `.Rproj` file after `use_course()`
cc @jaredlander

Open .Rproj if present after use_course()

---

R/github-labels.R
man/use_github_labels.Rd

* Adds section describing use of labels for issue triage.
* Gives rough definitions for each label included.
* Fixes #252.
* https://gist.github.com/batpigandme/3efba27ba8e62f731ef6016cf5370513
* https://help.github.com/articles/about-labels/#using-default-labels

Document usage for tidyverse labels 🏷

---

NEWS.md
R/edit.R
R/helpers.R
R/pkgdown.R
R/r.R
R/rcpp.R
R/test.R
R/vignette.R
man/edit.Rd
tests/testthat/test-edit.R
tests/testthat/test-use-dependency.R

Path handling will get even better once I tackle #177 (Use fs when released). Please view this as incremental progress in order to achieve this:
* `edit_git_ignore(scope = "user")` should message if user-level `.gitignore`is created *de novo*, as `edit_r_profile()` and `edit_r_environ()` do. Until you edit `core.excludesfile` in git config, the new gitignore file has no effect. But in order to do that, you need to separate path formation from path creation & editing.
* Fixes #181 (`edit_git_ignore("user")` should explain how to put file into force).
Fixes #182 (Be more flexible re: name of global gitignore file).
Return path, invisibly, from all `edit_*()` functions.
I think overall it is more convenient to edit a path than to edit a subpath within a basepath, given the helpers …

Work on edit_*() functions

---

inst/templates/tidy_contributing.md

* Removes long-form explanation for contributing.
* Changes PR process to bulleted list.
* References external guide to be housed at tidyverse.org.
* Fixes #236.

Cut down contributing template ✂️

---

R/ci.R

- Removes extra slash between `github` and `gh$username`
- Removes extra slash between `gh$repo` and `?branch=master&svg=true`

remove extra path separators

---

R/ci.R

To be consistent with the other badges, so that only the first word in the link text is capitalized:
```rmd
[![Travis build status](https://travis-ci.org/r-lib/usethis.svg?branch=master)](https://travis-ci.org/r-lib/usethis)
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/r-lib/usethis?branch=master&svg=true)](https://ci.appveyor.com/project/r-lib/usethis)
[![Coverage status](https://codecov.io/gh/r-lib/usethis/branch/master/graph/badge.svg)](https://codecov.io/github/r-lib/usethis?branch=master)
[![CRAN status](http://www.r-pkg.org/badges/version/usethis)](https://cran.r-project.org/package=usethis)
```

sync badge link text capitalization pattern

---

R/badge.R
R/ci.R
R/helpers.R
R/style.R

- Replaced `paste` or `paste0` with `file.path` wherever it made path construction faster
- Removed `file.path` when used within `paste0`
<details>
<summary>Benchmarking</summary>
```r
library(microbenchmark)
pkg <- "usethis"
microbenchmark(
src <- paste0("http://depsy.org/api/package/cran/", pkg, "/badge.svg"),
src <- file.path("http://depsy.org/api/package/cran", pkg, "badge.svg")
)
microbenchmark(
href <- paste0("http://depsy.org/package/r/", pkg),
href <- file.path("http://depsy.org/package/r", pkg)
)
microbenchmark(
src <- paste0("https://www.r-pkg.org/badges/version/", pkg),
src <- file.path("https://www.r-pkg.org/badges/version", pkg)
)
microbenchmark(
href <- paste0(
"https://bioconductor.org/checkResults/release/bioc-LATEST/",
pkg
),
href <- file.path( …
```

Fast file path

---

DESCRIPTION
tests/testthat/test-use-readme.R
tests/testthat/test-use-tidy-style.R
tests/testthat/test-vignette.R

We have previously tried to keep the stringr / stringi dependency out of devtools, however it snuck back in via rmarkdown. It looks like this was always meant to be a soft dependency (hence the calls to `check_installed()` but it was accidentally put in the wrong place in the DESCRIPTION.
I also moved styler as well, since it too can be a soft dependency.

Make rmarkdown a soft dependency

---

R/github.R
man/use_github.Rd

* Make `create_package()` example a valid package name.
* Fixes #319.

Change test-pkg to test.pkg.

---

R/test.R

This removes the test- prefix and .R extension, to match the generated
context in https://github.com/r-lib/testthat/pull/738

Simplify the default context

---

R/rmarkdown.R
tests/testthat/test-use-rmarkdown.R

A simple change of `yml` to `yaml` to increase compatibility.
* fixes #331

Correct the extension for YAML template in use_rmarkdown_template

---

R/github.R
man/use_github.Rd

Previously you would get the error 
> Error: URL has a different value in DESCRIPTION. Use overwrite = TRUE to overwrite.
But there was no way to actually pass `overwrite = TRUE`.
Fixes #316

Expose overwrite parameter in use_github_links

---

R/roxygen.R
man/use_roxygen_md.Rd

`use_roxygen_md()` references the roxygen2md package. This PR adds a hyperlink to the roxygen2md repo for easier directing from the package docs.

Added link to roxygen2md package

---

R/package.R
tests/testthat/test-use-package.R

Fixes #172 use_package("tidyverse|devtools") should generate a warning
So far, I'm just refusing to add the dependency and not adding all the individual packages. I don't really think we want people depending on every single package in the tidyverse either. I think it's OK to ask people to figure out what they need, yes?

Don't help people depend on tidyverse or devtools

---

R/code-of-conduct.R
R/tidyverse.R
man/use_code_of_conduct.Rd

Fixes #352 
* Specify the name of the project
* "participating" --> "contributing to" in the README sentence
* Removed `.md` from `README.md` to avoid the whole `.Rmd` vs `.md` thing
@batpigandme We are already using Contributor Covenant 1.0 and not 1.4, fwiw.

Sharpen wording around the code of conduct

---

R/helpers.R

Main points:
* Moved the GitHub stuff out of `package_data()` and into `project_data()`, so that it's also available for non-package projects.
* Use `github_owner()` and `github_repo()` helpers I recently added. (*They were added because we were doing this all over the place and it's awkward because two pieces of info.*)
* Always refer to GitHub "owner" because works equally well for individual users and orgs. It also matches GitHub API terminology.
* Consult  `project_data()` in `project_name()`, instead of re-implementing similar logic re: DESCRIPTION or basename of path.
Question: we have an `is_proj()` helper. Should we use it in `project_data()` instead of being so easy-going? `is_proj()` will return `TRUE` if the target path fulfills any of our `proj_crit()`, which we pass along to …

Refactor project data helpers

---

DESCRIPTION

Fixes #351 Aggressively state minimum versions of dependencies
clipr and rprojroot are concrete examples where we use specific functions that I can see were added at a specific version, based on reading NEWS.
I contemplated every other package in Imports and Suggests and couldn't find a specific reason to state a minimum version.
How aggressive should I be?
Any vague notions that I should put a floor on anything else?

Put a floor on clipr, rprojroot

---

NEWS.md
R/course.R

Fixes #276 Refactor use_course()
Thanks @jeroen for all the pointers!
Key things:
* Explicit use of a handle is how we hook into progress
reporting, even though curl_download() doesn't expose
* curl_download() has a built-in check for http status 200
* Using a custom progressfunction because default doesn't
always look right in RStudio
* Switch to fs functions for file system work

Refactor use_course() and gain progress reporting

---

DESCRIPTION

styler `v1.0.2` is now available on CRAN and I suggest to add a minimal version dependency to usethis to import this version. Most notable fixes (including critical fixes like implicit dependency removal) were already present in a prior release `v1.0.1`, but currently, usethis does not specify a minimal version for styler. You can find the changelog for the styler releases [here](http://styler.r-lib.org/news/index.html).

Adding minimal version requirement for styler

---

R/tidyverse.R

This avoids erroneously including issues which were merely updated after
the from timestamp

Filter results for only issues created after the from_timestamp

---

.Rbuildignore
R/create.R
R/proj.R
R/zzz.R
man/proj_get.Rd
principles.md
tests/manual/manual-create-from-github.R
tests/testthat/helper.R
tests/testthat/test-create.R
tests/testthat/test-proj.R
tests/testthat/test-write.R

Fixes #390 When rstudio = TRUE, don't change active project in create_package()
Generally tightens up project activation:
* ~Quietly attempt to activate project on load (should this be on attach?)~
* Announce project activation, by default
* Rename `is_proj(path)` to `possibly_in_proj(path)` to better reflect what it actually reports
* ~Store current project *and the previous*, so we can have `proj_revert()`~

Project activation

---

R/course.R

The `keep_lgl` function is very handy to ensure certain files and folders are removed when using `use_course`. Two other candidates are the "__MACSOSX" directory and ".DS_Store". This PR adds to the default value for the `ignores` argument.

Add "__MACOSX" and ".DS_Store" to ignores

---

R/badge.R
R/logo.R
R/news.R
R/rstudio.R
R/template.R
R/write.R

This is a small fix that adds the encoding argument to all `readLines()` calls in `R`. 
I noticed that the LICENSE.md file had some encoding issues when adding it via e.g. `use_gpl3_license()` (on Windows of course). Line 5 would for example read: 
`_Copyright Â© 2007 Free Software Foundation, Inc. &lt;<http://fsf.org/>&gt;_`
The problem is, is that incoming strings are not marked as "UTF-8". I tracked the problem to `use_template` which calls `readLines` without the `encoding` argument, which on Windows means that they are assumed to be in the "native" encoding. All template files are UTF-8 encoded, however. So I added `encoding = "UTF-8"`. 
I assume that all files generated and read by usethis are also supposed to be UTF-8 as well, so I looked up the other `readLines` calls in `R` as …

add encoding argument to readLines calls

---

R/tidyverse.R

In `use_tidy_thanks()` this replaces the `@` symbol with `&#xFF20;` (per clever suggestion of @hadley) to avoid an issue where RStudio runs pandoc-citeproc to lookup each of the referenced GitHub handles. 
🎉 Renders correctly! (see https://github.com/tidyverse/tidyverse.org/pull/194)

Replace @ with HTML ref.

---

R/logo.R

Previously `use_logo()` assumed png, or something which could be converted to png, so svg's were resized unnecessarily, as they are vector graphics.

Support svg logos in use_logo

---

R/data.R
R/description.R
R/license.R
R/namespace.R
R/news.R
R/package.R
R/r.R
R/readme.R
R/test.R
R/version.R
R/vignette.R
man/licenses.Rd
man/use_data.Rd
man/use_description.Rd
man/use_namespace.Rd
man/use_news_md.Rd
man/use_package.Rd
man/use_r.Rd
man/use_readme_rmd.Rd
man/use_testthat.Rd
man/use_version.Rd
man/use_vignette.Rd

This is a start at addressing #191 which adds links to relevant sections of the R packages website. 
I'm not sure how exhaustive the linking should be so I've assumed this PR alone isn't enough to close the issue. 
I hope this helps!

add seealso links to R packages website

---

tests/testthat/helper.R
tests/testthat/test-create.R

Fixes #250 scoped_temporary_thing(): should the directory be deleted upon frame exit?
Sanity check: I ran this:
``` r
test_that("something", {
scoped_temporary_package("~/tmp/a123")
Sys.sleep(10)
})
```
while staring at `~/tmp`. The folder `a123` appeared, persisted while the test was "running" then disappeared when the test completed.

Delete temporary projects/packages

---

R/version.R

This would fix #463, leading to graceful exit if the user selects "0" after calling `use_version()` without arguments.

Exit gracefully when calling use_version() and then selecting "0" - fixes #463

---

NEWS.md
R/create.R
R/github.R
man/create_from_github.Rd
man/use_github.Rd

This is an implementation that closes #492 feature request. 
* Keep the "ssh" the default behaviour
* Continue to match `protocol` to `"https"` or `"ssh"`
There are no tests about protocol in https, only manual test with ssh protocol. I could add some for protocol https but I won't be running the manual tests so let me know what you wish on this. 
About `match.arg`, I wanted to use `rlang::arg_match` but it is not use yet so I comply with the current standard for _usethis_. I can do another PR about migrating to `rlang::arg_match`. Error message would be clearer and there would be no partial matching, which is interesting here for `protocol` argument.

Add option usethis.protocol to change default globally 

---

NEWS.md
R/browse.R
R/ci.R
man/ci.Rd
tests/testthat/test-browse.R

This closes #349 by providing a way to choose `https://travis-ci.com/` instead of `https://travis-ci.org/`. 
The website url does not impact .travis.yml but is used to create the badge link and open a browser to activate travis on a project. 
This follows the announcement from travis: [Announcing support for open source projects on travis-ci.com](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps)

add a parameter to choose travis-ci .org or .com

---

R/description.R

example code in @description of the roxygen documentation has colon and unqouted string

typo in @description section

---

NEWS.md
R/pkgdown.R
man/use_pkgdown.Rd

Make use_pkgdown configurable

---

R/edit.R
tests/testthat/test-edit.R

This was causing test failure for me locally, in the test I've edited:
```
>   expect_equal(path1, as.character(path2))
Error: `path1` not equal to as.character(path2).
1/1 mismatches
x[1]: "/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T//RtmpMtS78Z/file167c347ea5
x[1]: f6b"
y[1]: "/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpMtS78Z/file167c347ea5f
y[1]: 6b"
```
It makes sense to treat a path stored in `R_PROFILE_USER` as a "user provided path" anyway.

Prepare externally-created paths under our policy

---

tests/testthat/helper.R
tests/testthat/test-roxygen.R
tests/testthat/test-use-badge.R
tests/testthat/test-use-dependency.R
tests/testthat/test-use-rcpp.R

This is how the helper should have been in the first place. Now it's symmetric: setup and teardown are both quiet.
This makes it easier to manipulate `usethis.quiet` in a test, i.e. you can use `withr::local_options()` instead of `withr::with_options()`.

Muffle setup and teardown of scoped_temporary_things

---

README.Rmd
README.md

Original link goes to 404 page. The `proj_get()` help page is wrapped within proj_utils page. These commits also update the links from `http` to `https`.

Fix broken link in README.{md,Rmd}

---

R/github.R

Fixing issue #569. 
This was a freebie 😁

remove comma from proj name in use_github

---

R/description.R
man/use_description.Rd
vignettes/articles/usethis-setup.Rmd

cf #108 in particular https://github.com/r-lib/usethis/issues/108#issuecomment-443096619
I'm not sure whether (not) to introduce a line break in `person()`.
I had been considering adding links to `desc` (convenience) functions but I'm not sure how to and it's actually maybe a topic for another issue.
* Making sure `whoami` finds all your info could be part of the recommended setup (in the setup article) but `usethis` doesn't use `whoami` at all, only `desc::desc_add_me()` does.
* `desc` convenience functions [support ORCID](https://github.com/r-lib/desc/pull/70) but their use is actually beyond setup, it's more about managing authors later in a package life?
End of long comment. 😸

Encourage ORCID use

---

R/github.R

I didn't have `usethis` library()d, so when I got the instruction to `Call edit_r_environ() to open...` I got a "could not find function" error.
With this change, I would have gotten it right on the first try.

Preface usethis function call with package name.

---

R/package.R

The `fun` reference caused me a bit of "foo confusion." I thought, "is there some magic where I'm supposed to refer to `mutate` like `dplyr::fun(mutate)(...)`?" This update hopes to close that line of confusion by focusing the user on direct reference like `dplyr::mutate`.

Clarify this help message with a bit of verbosity. 

---

NEWS.md
inst/templates/tidy-eval.R

Closes #595 .
I didn't add a test, because the current test doesn't actually check the contents of the file (only that it exists), and I was already a bit lost in how that test works. I can take a stab at a more specific test if you'd like, though.

Re-export := in use_tidy_eval().

---

R/git-utils.R
R/git.R
R/pr.R

This includes:
* `git_branch_remote()` -> `git_branch_tracking()`
* Pretending the master branch of a fork tracks `upstream/master` not `origin/master`
* Looking for the correct remote when checking a branch is up-to-date

Better approach to remote branches

---

_pkgdown.yml

This addresses issue #594. 
I took my best guess for where to place this section in the `_pkgdown.yml`. 
Also noting that the following are missing from the pkgdown index:
`Warning: Topics missing from index: git_sitrep, git_vaccinate, pr_init, use_citation, use_github_release, use_release_issue`

add ci section to index use_travis and use_appeyor on pkgdown site

---

NEWS.md
R/rstudio.R

See discussion in https://github.com/r-lib/usethis/issues/571#issuecomment-459733807
This PR is a simple modification to `in_rstudio()` such that this function returns `FALSE` when called from an RStudio session without an active project.
In this case, `rstudioapi::getActiveProject()` returns `NULL`, which caused `path_real()` to throw an error.
```
Error in enc2utf8(path) : argument is not a character vector
```

Fix #571 in_rstudio() returns FALSE if in RStudio and no active project

---

R/release.R
R/version.R

Supports calling `use_release_issue()` without knowing the right version in advance, i.e. helps you specify the version:
```
> proj_set("~/rrr/readxl")
✔ Setting active project to '/Users/jenny/rrr/readxl'
> use_release_issue()
Current version is 1.2.0.9000.
Which part to increment? (0 to exit) 
1: major --> 2.0.0
2: minor --> 1.3.0
3: patch --> 1.2.1
4:   dev --> 1.2.0.9001
Selection: 2
✔ Opening URL 'https://github.com/tidyverse/readxl/issues/553'
```

Expose version-choosing logic in use_release_issue()

---

inst/templates/appveyor.yml

Currently this is not set, leading to `testthat::skip_on_cran()` to also skip tests on Appveyor.  Users should explicitly use `skip_on_appveyor()` to also skip appveyor tests. Closes #641.

Set NOT_CRAN environmental variable

---

_pkgdown.yml

I don't know if this is premature or not, but it will help me find the reference more-easily on the dev pkgdown site.

Add pr_*() family to the pkgdown function-references

---

R/release.R

We still have a problem that `use_version()` doesn't quite have the right semantics — it adds a new heading to NEWS instead of replacing the existing.

Embed release type in use_version() call

---

NEWS.md
R/rmarkdown.R
R/test.R
R/utils.R
man/use_rmarkdown_template.Rd
man/use_testthat.Rd
tests/testthat/test-utils.R

Check file name for non-ascii characters, remove `asciify()` from `slug()`, remove `tolower()` from `asciify()` to ensure name fidelity, update unit tests accordingly.
Fixes #581

Check file name for non-ascii characters and remove tolower() to ensure file name fidelity in use_test()

---

R/git-utils.R

Creating a branch with a slash in the name in order to fix #670

Anticipate PR branch names that contain a slash

---

R/create.R
R/git.R
R/github-labels.R
R/github-utils.R
R/github.R
R/pr.R
R/release.R
tests/manual/manual-create-from-github-https-private-repo.R
tests/manual/manual-create-from-github.R
tests/manual/manual-use-github.R
tests/testthat/test-create.R
tests/testthat/test-github-utils.R

Closes #657 Where to check validity of GitHub PAT?
Notes to self are in the issue. Highlights:
* Put definitions and checks closer to where they are used.
* `""` is the PAT when we have no PAT. This is expedient, because it's what gh expects.
*  We have two levels of PAT checking:
- ~`validate_github_token()`~ `check_github_token()` does a rigorous check, including against the GitHub API. Use this when we know we truly need a token or git credentials.
- ~`maybe_github_token()`~ `check_github_token(allow_empty = TRUE)` tolerates `""` but, otherwise, does full checks. Use this when we can get away with having no token or credentials, i.e. reading a public resource.

Refactor handling of GitHub token

---

NEWS.md
R/data.R
man/use_data.Rd
tests/testthat/test-use-data.R

Closes #675
From R News:
https://cran.r-project.org/doc/manuals/r-devel/NEWS.html
CHANGES IN R 3.6.0
SIGNIFICANT USER-VISIBLE CHANGES
Serialization format version 3 becomes the default for serialization and saving of the workspace (save(), serialize(), saveRDS(), compiler::cmpfile()). Serialized data in format 3 cannot be read by versions of R prior to version 3.5.0. Serialization format version 2 is still supported and can be selected by version = 2 in the save/serialization functions. The default can be changed back for the whole R session by setting environment variables R_DEFAULT_SAVE_VERSION and R_DEFAULT_SERIALIZE_VERSION to 2. For maximal back-compatibility, files ‘vignette.rds’ and ‘partial.rdb’ generated by R CMD build are in serialization format version 2, and resave by default …

Use serialization format version 2 by default in use_data()

---

R/git-utils.R
R/git.R

Fixes #708
Use this to change our default for git_ask_commit() to NOT include untracked files.

Create way to pass args to git2r::status()

---

inst/templates/tidy-eval.R

https://adv-r.hadley.nz/introduction-16.html
should be: 
https://adv-r.hadley.nz/metaprogramming.html

Fix broken link

---

inst/templates/tidy-eval.R

* Reexport `as_name()` and `as_label()` instead of `quo_name()`
* No longer reexport `enexpr()` and `enexprs()` which should basically never be used.
* No longer reexport `quo()` and `quos()` which are rarely useful. Keep `expr()` which should be used instead.
* Revisit documentation.

Fix tidy eval template

---

R/create.R
man/create_from_github.Rd
man/use_jenkins.Rd

Closes #746
Added @section on authenticating to GitHub in the `create_from_github()` docs. The hope is that this addition will help Windows users who want to authenticate via SSH. I collaborated with @jennybc on this PR, which addresses #746.

Make authentication to GitHub via SSH keys easier on Windows users. (#746)

---

R/badge.R

Binder has a new badge now with a logo, see https://discourse.jupyter.org/t/help-us-choose-an-updated-launch-binder-badge/100/21
Also changed the protocol to https, to which http is redirected.

Update binder badge URL

---

R/description.R
R/r.R
tests/testthat/test-helpers.R

Use stricter regexes for package and file name checks

---

NEWS.md
R/create.R
man/create_from_github.Rd
tests/testthat/test-use-circleci.R

Before:
master --> origin/master
After:
master --> upstream/master
Now `git pull` will pull from upstream in a fork. This feels like a more correct setup to leave people with.

Set upstream tracking branch for master in a fork

---

R/git.R
R/news.R
tests/testthat/test-use-version.R

This PR allows you to call `use_version("major")` when you are currently in a state where the first line of NEWS is `# pkg (development version)` and directly replace that header with the bumped version. This means you no longer have to manually delete the temporary dev header.

`use_version()` directly replaces development version NEWS headers

---

NEWS.md
R/github.R
R/template.R

Fixes #493 with a simple `gsub` so that titles with newlines do not break the push to GitHub.  Also, added a space in the text when failing on template.

Newline fix 

---

inst/templates/pipe.R

This change will prevent Rd warnings during "Install and Restart" on Windows. However, it may make the link more fragile.
https://github.com/klutometis/roxygen/issues/707
https://stackoverflow.com/questions/48430093/how-do-i-resolve-rd-warning-missing-file-link-when-building-packages-in-rstudi/48478698#48478698

Link to topic file and not alias (pipe)

---

R/release.R

This is a simple code typo, the `if (length(headings == 1))` statement shouldn't be there. The idea is that if the user's `NEWS.md` file has no top-level headings, then they get the error "No top-level headings found in {ui_value(path)}" but right now what actually happens is that the code falls through to `text <- which(news != "")` and `news` doesn't exist there so the user gets an uninformative error from that.
Sorry for no reprex, kinda hard when the function is searching for a file with a certain name within the current project.

Fix bug in news_latest().

---

R/edit.R
R/rprofile.R

This PR changes the order of the messages that the user sees when editing the Rprofile and the Renviron file as proposed on #732.

Reorder the messages in edit_r_profile, edit_renviron and rprofile-helper functions

---

NEWS.md
inst/templates/packagename-data-prep.R

Resolves #736
```r
usethis::use_data_raw("daisy")
```
```
usethis::use_data(daisy, overwrite = TRUE)
```

Updated `use_data_raw()` template for unquoted use_data and overwrite

---

R/tutorial.R
tests/testthat/test-use-tutorial.R

Addresses #782:
> use_tutorial() creates R Markdown files in inst/tutorials/ as single files. But learnr requires them in individual folders
@angela-li  @isteves

fix #782: creates file in correct location: a new directory 

---

R/ignore.R
man/use_build_ignore.Rd

Fixes #722 
Ready for review.
Adds an example to `use_build_ignore()` to show how to ignore all files that have a given extension.
I tested this manually, the example works for me. It is unclear how to test this, but I am happy to attempt it if you would like.
As well, I did not think this merits a NEWS item, but will be happy to add an item if you like.

Add example to use_build_ignore()

---

R/ci.R
inst/templates/circleci-config.yml
tests/testthat/test-use-circleci.R

I used `use_circleci()` today and found a few bugs:
* The mustache delimiters caused the cache keys to be corrupted. I fixed this by using alternative delimiters, as suggested [here](https://mustache.github.io/mustache.5.html)
* `R CMD build` mentioned that it removed the empty `.circleci` directory. Apparently ignoring the only file it contains doesn't also ignore the entire directory. Thus I also explicitly ignored the directory itself
I added tests for both of these updates and also ran styler on the code changes.

Fix use_circleci

---

NEWS.md

I forgot to add a NEWS bullet for my fix in PR #835. Since the version of `use_circleci()` in the current CRAN release (1.5.1) contains the bug, it will be useful for users to know they need to install the development version to use `use_circleci()`.

Add NEWS bullet for CircleCI fix in PR #835.

---

NEWS.md
R/create.R
R/description.R
man/create_package.Rd
man/use_description.Rd
tests/testthat/helper.R
tests/testthat/test-use-description.R

- `stop_for_name` controls whether to throw error
for invalid CRAN package names
- Default to warning for `use_description()`, error
for `create_package()`
- Add tests
- update NEWS
I am unsure if `stop_for_name` is the best argument name, open to other suggestions!
Closes #528

Allow invalid CRAN names

---

NEWS.md
R/directory.R
R/rcpp.R
man/use_rcpp.Rd

Fixes #720
This PR modifies both `use_rcpp()` and `use_c()` to ensure at least one source file is present in `src/`. Previously, if a source file wasn't present but the `src/` directory was, then the package would error on build.
In addition, this PR adds two new functions into the `directory.R` variant related to counting files in a directory.

Ensure src/ always has a code file (#720)

---

R/license.R
man/licenses.Rd
tests/testthat/test-use-license.R

Closes r-lib/usethis#898 by using the proper license abbreviation as defined by the R project license documentation on [line 259](https://github.com/wch/r-source/blob/886ab4a0b7536c62fcb7c02d8a76430510d2c396/share/licenses/license.db#L259):
> Name: Creative Commons Attribution 4.0 International License
> **Abbrev: CC BY 4.0**
> FSF: free_and_GPLv3_incompatible
> URL: https://creativecommons.org/licenses/by/4.0
> FOSS: yes
> Extensible: yes
By using "CC BY 4.0" over "CCBY-4.0" packages made with `usethis::use_ccby_license()` pass the `devtools::check()` without any warnings.
```
── R CMD check results ── issue 0.0.0.9001 ──
Duration: 3s
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```
Previously, `devtools::check()` returned a warning that a "non-standard" license was being used.
```
── R CMD …
```

Use proper abbrev in use_ccby_license()

---

NEWS.md
R/edit.R
man/edit.Rd
tests/testthat/test-edit.R

Restrict options of snippet types and warn if the default snippets are masked.
Closes #885

Restrict options of snippet types

---

DESCRIPTION
NEWS.md
R/ui.R
revdep/README.md
revdep/failures.md
revdep/problems.md
tests/testthat/test-roxygen.R
tests/testthat/test-use-badge.R
tests/testthat/test-use-course.R
tests/testthat/test-use-dependency.R
tests/testthat/test-use-pipe.R
tests/testthat/test-use-tibble.R

But output the messages on stdout instead of stderr, to avoid red text
in RStudio and the Windows GUI.
This works around the issues with `message()` in RStudio by outputting the results on standard output rather than stderr, but still lets us emit message conditions objects, so they can be easily muffled by users with `suppressMessages()` and friends.
I recently used a similar approach in vroom, I think it handles the largest downside of using `message()` while giving the benefits of muffling without having to resort to `capture.output()`.
I did not try to edit the relevant sections of principles.md in regards to this.

Use messages rather than cat to output

---

R/ui.R

rlang::inform() already appends a newline

Do not append a newline to the lines

---

R/github-actions.R

Closes #944 
Linking directly to the GitHub Actions page on the repo will 404 if you are not signed into GitHub, which makes CRAN check unhappy.
i.e. try going here in an incognito window:
https://github.com/r-lib/vctrs/actions?workflow=R-CMD-check
The suggestion in #944 is just to link to the repo URL, so that is what I've done here.

Link GitHub Actions badge to repo URL

---

inst/templates/tidy-eval.R

The quotation page was broken into several subpages, so the links needed to be updated to prevent warnings.

Update template to correct links to rlang docs

---

R/helpers.R

There was a missing space in this UI warning

Missing space, misc. change.

---

R/pkgdown.R

as `pkgdown::build_favicon` is deprecated

use build_favicons instead of build_favicon

---

R/data-table.R

I'm using`use_data_table()` in our rstudio::conf workshop next week, and I noticed the template file name   was wrong. This PR fixes it.

fix dt template typo

---

NEWS.md
R/logo.R

```
> usethis::use_logo("hex/icon.svg")
✔ Copied 'hex/icon.svg' to 'man/figures/logo.svg'
● Add logo to your README with the following html:
[Copied to clipboard]
```
This PR fixes the URL `https:/*` to be `https://*`. I don't think treating the URL as a path here is necessary, as it is from pkgdown config.

Fix use_logo url converting https://* to https:/*

---

R/code-of-conduct.R
inst/templates/CODE_OF_CONDUCT.md
man/use_code_of_conduct.Rd

When submitting a package of mine to CRAN this morning, I receive a reply noting that the link in my README (to the [contributor-covenant.org](https://contributor-covenant.org)) website was "invalid".
Turns out that 1.0.0 version has moved; you can still find that version if you use hyphens in the URL. However, you can also access latest 2.0 version using underscores. Kind of odd.
Using either approach would solve the problem, I don't know if you want to update to the newer version.
I just read the 2.0 markdown directly and wrapped it to 80 characters width. Then I replaced all the instances of the old version with the new version.
``` r
old_code <- readr::read_lines("R/code-of-conduct.R")
cat(old_code[34:35], sep = "\n")
#>   href <- project_pkgdown_url() %||% …
```

Use 2.0 code of conduct

---

tests/testthat/test-use-data-table.R

Closes #984 
(I am using a mock roxygen check here, but `use_data_table()` doesn't currently check for roxygen despite using `@import`. Will add a separate issue for that.)

add tests for `use_data_table()`

---

R/data-table.R

`use_data_table()` doesn't currently check for roxygen, but as this implementation uses `@import`, it seems essential, as in the case of `use_tibble()`. This PR adds a check.

Check for roxygen in `use_data_table()`

---

R/github-actions.R

GitHub now provides a /actions URL which is accessible even when users
are not logged in, so we can now link to that

Use better link for the GitHub Actions badge

---

R/github-action.R
R/tidyverse.R
tests/testthat/test-github-actions.R

Rather than trying to ignore individual files. This way is simpler and
less fiddly if you later add other workflows.

Ignore the whole .github folder

---

R/create.R
tests/testthat/test-create.R

Fixes #777
I think this should be safe because it's only affects the name of the package, and it doesn't break any tests, but I'd appreciate a second pair of eyes

Allow create_package() to use "." once more

---

R/pr.R
man/pr_init.Rd
vignettes/articles/pr-functions.Rmd

Context: in rOpenSci blog guidance we recommend opening a draft PR first, and mention `usethis`' excellent PR helpers. I started wondering whether the docs of `usethis`' PR helpers should mention draft PRs. :slightly_smiling_face:

Suggest adding mention of draft PR in PR helpers' docs

---

DESCRIPTION
NEWS.md
R/browse.R
R/ci.R
R/tidyverse.R
man/browse-this.Rd
man/ci.Rd
man/proj_utils.Rd
man/tidyverse.Rd
tests/testthat/test-browse.R

Fixes #1038.
* travis-ci.com is now recommended over travis-ci.org.
* Documented with newly-released roxygen2.

`use_travis()` and friends now point to travis-ci.com by default.

---

R/github-actions.R

Rather than running test coverage after the check finishes, this action
runs it as a separate workflow
This can be useful when a package takes a while to compile and check, as
covr needs to recompile it anyway and measuring the coverage does not
really depend on a successful check

Use separate test-coverage action to run test coverage

---

DESCRIPTION
NEWS.md
R/browse.R
tests/testthat/test-browse.R

If `package` is NULL, `gitub_home()` starts by looking in the upstream remote, followed by the origin. If package isn't NULL, it looks in BugReports, then URL.
I've eliminated github_link() because it's too hard to make it work across a wide range of packages.
Fixes #1023
This is important for GitHub actions because they use `github_home()` to construct the badge.

Look in remotes for github_home()

---

R/vignette.R

This is technically wrong, but it's such a rare case that I doubt it will cause any problems in practice.
Fixes #773

Overwrite VignetteBuilder if already set

---

R/course.R
man/create_from_github.Rd
man/use_course_details.Rd
man/zip-utils.Rd
tests/testthat/test-use-course.R
vignettes/articles/usethis-setup.Rmd

Closes #1015.
This PR adds an option `usethis.destdir` to set a default directory for use in `create_from_github()` and `use_course()`, describes it in the relevant docs and setup vignette, and adds a test.
Note that I also added a brief description about `usethis.quiet` to the setup vignette, since it was missing. If this PR is not accepted, I'd be happy to submit a smaller one that has that, since it should probably be there.
I'll admit that, while I think this would be a very useful feature, there's a little bit of an inconsistency. `use_zip()` and `use_pkgdown()` both also have `destdir` options that have defaults. `use_pkgdown()` is perhaps less of an issue but `use_zip()` is closely related to `use_course()` and even shares a help page with it.

add option `usethis.destdir`

---

.github/workflows/R-CMD-check.yaml

Fixes #1070
Lesson learned along the way: the git config has to be global, not local, if it needs to be in force inside the scoped temporary projects we used widely in the tests.

Configure a dummy git user

---

R/write.R
tests/testthat/test-write.R

This is the root cause of what we were talking about in https://github.com/r-lib/usethis/pull/1072#pullrequestreview-380448740 (my initial comment was off-base, but this was worth sorting out).

Ensure we can write_utf8() even when outside a project

---

R/create.R
R/utils.R
tests/testthat/helper.R
tests/testthat/test-browse.R
tests/testthat/test-create.R
tests/testthat/test-proj.R
tests/testthat/test-use-course.R

Related to the "Can we remove `is_testing()` too?" comment in https://github.com/r-lib/usethis/pull/1084#pullrequestreview-384684789
This removes `is_testing()` and does a general tidy up around nested projects.

Clean up code and tests around nested projects

---

R/lifecycle.R
man/edit.Rd
man/use_lifecycle.Rd

(`http://lifecycle.r-lib.org` doesn't redirect to its HTTPS counterpart)

Use secure URL

---

R/r.R
R/test.R

Hides the first TODO item shown currently:
``` r
pkg <- rlang::with_options(
usethis.quiet = TRUE,
usethis::create_package(tempfile("pkg"))
)
usethis::proj_set(pkg)
#> ✓ Setting active project to '/tmp/Rtmp7WyA5K/pkg4c967aa89a98'
usethis::use_test("super")
#> ✓ Adding 'testthat' to Suggests field in DESCRIPTION
#> ✓ Creating 'tests/testthat/'
#> ✓ Writing 'tests/testthat.R'
#> ● Call `use_test()` to initialize a basic test file and open it for editing.
#> ✓ Writing 'tests/testthat/test-super.R'
#> ● Edit 'tests/testthat/test-super.R'
```
<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Avoid message after use_test() in uninitialized package

---

R/package.R
tests/testthat/test-package.R

This PR adds tidymodels to `verboten`, to be handled in the same way that tidyverse is within `add_package()` and `refuse_package()`. This addresses tidymodels/tidymodels#3.

Add tidymodels to refuse_package()

---

vignettes/articles/pr-functions.Rmd

This PR fixes the background coloring for reviewer and output chunks in the [pull request helpers](https://usethis.r-lib.org/articles/articles/pr-functions.html) vignette. It seems like the class for these chunks have changed over time. I haven't dug into why the change happened but this minor fix should display the colors correctly.
Closes #1186.

Fix background color for reviewer and output chunks in vignette

---

R/tutorial.R

Fixes #1178 
It changes the `use_tutorial` function so the tutorial `Rmd` is no longer added in `.Rbuildignore`, which now makes the tutorial discoverable to `learnr::run_tutorial`. 
On the other hand, it now build ignores  the `html` file generated from rendering the tutorial.

Fix use_tutorial

---

.github/workflows/R-CMD-check.yaml

It is not included in the system requirements database because it
conflicts with libcurl4-openssl-dev. But the `setup-r` action include
the travis ppa which has a backport for libgit2-dev which does work
without conflicts

Manually install libgit2-dev

---

tests/testthat/setup.R
tests/testthat/test-github-actions.R
tests/testthat/test-roxygen.R
tests/testthat/test-ui.R
tests/testthat/test-use-badge.R

Turned out to be simpler than I expected, and I think the payoff (nicely coloured tests) is worth it. The only minor head scratcher was finding the `on.exit()` with missing `add = TRUE`.

Only disable crayon for individual tests

---

R/github-actions.R

This PR updates `use_github_actions_badge()` to more generally support GHA badges, using `name` instead of "R build status". This essentially maintains the default behavior (the Rmd link and `ui_done()` message now say "R-CMD-check" instead of "R build Status", but the appearance of the badge itself does not change) while giving more informative messages when you're adding a badge for a different type of workflow besides "R-CMD-check".

Use `name` instead of "R build status" in GHA badge

---

R/utils-git.R

Make code robust against potential re-ordering, missing, or additional fields in `ahead_behind()` output.

Make ahead-behind more robust

---

R/tidyverse.R
R/utils.R

It looks like these functions used an idiosyncratic pluck_chr() that was really a map_chr(). A some point a proper pluck_chr() was added, breaking use_tidy_thanks()

Get use_tidy_thanks() working again

---

R/git.R
R/github_token.R
R/ui.R
R/utils-github.R
R/utils.R
man/git_vaccinate.Rd
man/github-token.Rd

Closes #1172, closes #1174, closes #1177

GitHub diagnostics

---

inst/templates/Makefile

In the `use_make()` template. Fixes #1138

Make install_deps a dependency of build

---

R/utils-github.R

cfg is a required argument in both check_for_bad_config()and check_for_maybe_config(). Not transferring into these creates a bug that keeps emitting error.

Transfer cfg object in check_ours_or_fork()

---

NEWS.md
R/version.R
man/use_version.Rd
tests/testthat/test-version.R

With this change, we check for existence of a src/version.c file with a line that matches `package_version = "VERSION"`. If there is a match, it is updated to the new version.
This is useful for projects like rlang or vctrs which check at load time that the version stored in the dynlib corresponds to the installed version. https://github.com/r-lib/rlang/blob/v0.4.9/src/version.c

Update `version.c` in `use_dev_version()`

---

R/course.R
man/zip-utils.Rd

/document
(I don't know if I have the authority to run the "document" action, we'll see)
Narrator: He did not have the authority.

fix typo in documentation

---

R/github_token.R

Brings host-specific feedback to `create_github_token()`.
This is very similar to #1291 - I waffled on attaching this change to that PR.

apply host_hint/code_hint to create_github_token()

---

R/usethis-defunct.R

Closes #1297 
``` r
usethis::pr_sync()
#> Error: `pr_sync()` was deprecated in usethis 2.0.0 and is now defunct.
#> Sync a PR with:
#>   * `pr_pull()`
#>   * `pr_merge_main()`
#>   * `pr_push()`
```
<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Fix hint of pr_sync() to include pr_push()

---

NEWS.md
R/lifecycle.R
man/use_lifecycle.Rd

The main purpose of this function is to import badges in `man/figures` and using lifecycle badges only requires a build time dependency.
Instead, we suggest using `usethis::use_dependency()` in case lifecycle functions are needed.

Don't import lifecycle package in `use_lifecycle()`

---

_pkgdown.yml

Fix a small typo in the menu about News.

Correct menu title for blog post v2.0

---

R/pr.R

There are several `ui_*()` calls that feel not-quite-right to me in `pr.R`; this PR swaps out several existing calls with other UI functions that feel more appropriate given the message.

Make UI calls more consistent in PR functions

---

NEWS.md
R/browse.R
R/github.R
R/proj.R
R/readme.R
R/tidyverse.R
R/tutorial.R
R/utils-github.R
R/vignette.R
tests/testthat/test-tidyverse.R

`project_data()` and related functions contain some outdated logic that `origin` is always the target remote. This function can actually be eliminated.
Closes #1312

Eliminate project_data()

---

R/pr.R

Fixes a small issue in a `glue()` string caused by a `NULL` value when 1 branch is not listed that creates a length-0 character, which eventually causes an error.
``` r
library(glue)
n <- 1
pre <- glue("{n} branch{if (n > 1) 'es'} not listed: ")
nchar(pre)
#> integer(0)
if (nchar(pre) < Inf) "go ahead and glue..."
#> Error in if (nchar(pre) < Inf) "go ahead and glue...": argument is of length zero
n <- 1
pre <- glue("{n} branch{if (n > 1) 'es' else ''} not listed: ")
nchar(pre)
#> [1] 21
if (nchar(pre) < Inf) "go ahead and glue..."
#> [1] "go ahead and glue..."
```

Fixes choose_branch() when one branch is not shown

---

R/git.R
vignettes/articles/pr-functions.Rmd

This little baby PR just adds a missing `ui_value()` when referring to the default protocol and updates the corresponding output in the PR vignette

Add missing `ui_value()` when referring to protocol

---

R/github-actions.R

Provide pointer to GHA docs

---

NEWS.md
R/vignette.R
tests/testthat/test-vignette.R

Put articles in correct place

---

R/release.R
R/version.R

This is a drastically simplified version of #1324. As mentioned there, I was confused by the prompt in `use_release_issue()`, identical to the prompt in `use_version()`, which made it sound like it was going to increment for me then and there.
This PR simply clarifies the message and doesn't touch any of the other issues mentioned in 1324. Unfortunately, I couldn't think of wording that worked for both cases that didn't make it sound like `use_release_issue()` was going to increment then and there, so I had to introduce a few more lines of code than I would have liked for such a simple PR.

Clarify `choose_version()` prompt for `use_release_issue()`

---

inst/templates/CODE_OF_CONDUCT.md

Seen here: https://usethis.r-lib.org/CODE_OF_CONDUCT.html
The template does have newlines in the wrong place

Fix links in CODE_OF_CONDUCT.md

---

.github/workflows/lint-undesirable-functions.yaml
tests/testthat/test-addin.R

In working on https://github.com/r-lib/devtools/pull/2331, I noticed that this linter (which I was using locally) was missing `system.file()`. It also doesn't seem like there is an fs equivalent of `tempdir()` (and fs itself seems to use `tempdir()`). I also updated a test using `system.file()`

Update fs linter

---

DESCRIPTION
R/description.R
tests/testthat/test-tidyverse.R

This PR bumps the desc dep to require 1.3.0. It also removes the code in `tidy_desc()` that sorts dependencies and remotes, instead letting `desc_normalize()` do it. Additionally, it improves the test for `use_tidy_description()` to check the order of remotes.
Closes #1394

Require desc 1.3.0

---

R/github-actions.R
man/use_github_action.Rd
tests/testthat/_snaps/github-actions.md
tests/testthat/test-github-actions.R

This PR exposes the `readme` argument in `use_github_action()` to allow users to specify the location of a readme. 
The purpose of this PR is to make it easier to point to documentation when writing wrappers for custom actions using the `url` argument.

Expose `readme` argument in `use_github_action()`

---

R/github-actions.R

I noticed a slight inconsistency in `use_github_action()` that used its own solution to managing extensions rather than fs. This PR updates that bit of code to use `path_ext_set()`. I don't think it needs to use the more surgical `slug()` since it's referring to an r-lib file that follows a predictable pattern

Use `path_ext_set()` to modify extension

---

R/utils-git.R
tests/testthat/test-git.R

- wrap both keys in `tolower()`
- add expectations to existing test
Fixes #1401

make git_cfg_get() case insensitive

---

man/tidyverse.Rd

Looks like a typo got fixed without rendering the matching doc. Let's get this little feller fixed up

Document dangling typo

---

R/edit.R
man/edit.Rd
tests/testthat/test-edit.R

This PR modifies `edit_r_buildignore()` to only work locally, not attempting to create a user-level `.Rbuildignore`. 
Fixes #1428

Modify `edit_r_buildignore()` to only work locally

---

R/github-labels.R

This PR adds a new label "upkeep" to the GitHub labels installed by `usethis::use_tidy_labels()`.

Add "upkeep" to tidy labels for GitHub

---

R/pr.R
R/utils-git.R

Closes #1449
Notes from analyzing the problem:
The problem occurs when a branch name is re-used for multiple PRs and then you try to `pr_finish()` or `pr_forget()` without specifying the PR number (i.e. you intend to discover the PR associated with the current branch) . Life is good is we already have the relevant PR recorded in the local git config.
Therefore, one half of this PR is about being more diligent to record a PR's URL during all possible `pr_*()` interactions. We were already recording it in the course of certain activities (`pr_fetch()`, `pr_view()`, `pr_push()`). But now we also do in `pr_resume()` and `pr_pull()`. The `pr-url` should now appear in local git config much more often.
The second half of this PR deals with the case where `pr_clean()` (called by `pr_finish()` and …

Improve PR targetting

---

R/rstudio.R

Presently `rappdirs::user_config_dir("RStudio", os = "unix")` fails in Linux due to case sensitive file paths (see https://github.com/charliejhadley/rstudioprefswitcher/issues/1).
Closes #1425

Correct casing in `rstudio_config_path()`

---

R/issue.R
man/issue-this.Rd

Currently, the `reprex` argument is incorrectly included in `issue_reprex_needed()` rather than `issue_close_community()` to the wrong function in the [examples for the GitHub Issue helpers](https://usethis.r-lib.org/reference/issue-this.html#examples).
This is a small PR to correct this.
At present, the example code-block in the [examples for the GitHub Issue helpers](https://usethis.r-lib.org/reference/issue-this.html#examples) is:
```
issue_close_community(12)
issue_reprex_needed(241, reprex = TRUE)
```
However, the `reprex` argument is only used in `issue_close_community()` not `issue_reprex_needed()`. The correct example code-block should read:
```
issue_close_community(12, reprex = TRUE)
issue_reprex_needed(241)
```
To correct this, I have made the necessary changes to the source R …

Fix small typo in examples in GitHub Issue helpers documentation

---

R/data-table.R

use_data_table() called desc::desc_get_deps(".") causing an error if working outside the project directory. This commit updates the call to desc::desc_get_deps(proj_get()) .
Closes #1534

use_data_table() outside of project directory

---

R/roxygen.R

Adds `path = proj_get()` to `pkgload::load_all()` call in `roxygen_update_ns()`.
Closes #1536

use_import_from() outside package directory

---

DESCRIPTION
R/tidyverse.R

Since roxygen2 now automatically squashes whitespace

No longer need to redocument after use_tidy_description()

---

R/pkgdown.R
man/use_pkgdown.Rd

As the branch is normally called `gh-pages`, not `github-pages`.

fix github pages branch name

---

R/pkgdown.R

For consistency, and since we're now gently encouraging as a default across RStudio.

Use is_rstudio_pkg() in use_pkgdown_github_pages()

---

R/code-of-conduct.R
inst/templates/CODE_OF_CONDUCT.md

Updates `use_code_of_conduct()`, and the associated wrapper functions (e.g. `use_tidy_coc()`, as well as the CODE_OF_CONDUCT.md template to use Contributor Covenant v. 2.1.

Update CoC to Contributor Covenant 2.1

---

R/tidy-upkeep.R
tests/testthat/_snaps/tidy-upkeep.md

Since `use_tidy_labels()` is deprecated

Use non-deprecated `use_tidy_github_labels()` in checklist

---

R/code-of-conduct.R

Changing the language in code-of-conduct.R from requiring ("don't forget) to suggesting ("you may also want to"). Since the Code of Conduct is linked in other locations, it's not required that it go in the README, but some projects may still want to include it, especially if they don't have other places, like pkgdown sites, where it's as documented.

updating language around README in code-of-conduct.R

---

R/release.R
R/tidy-upkeep.R
tests/testthat/_snaps/tidy-upkeep.md
tests/testthat/test-release.R
tests/testthat/test-tidy-upkeep.R

Fixes #1600 
in `person()`,  `given` field can be NULL which does not play well with `==` comparaison. In that case `is_rstudio_funded()` won't return TRUE or FALSE, but NA. 
Using `identical()` fix the issue.
I can add a NEWS bullet for this if needed.

Account for more ways that RStudio can appear in pkg author's (or not appear)

---

tests/testthat/setup.R
tests/testthat/teardown.R

A small PR that removes `teardown.R` in favor of `teardown_env()`

Switch to `teardown_env()`

---

DESCRIPTION
NEWS.md
R/data.R
man/use_data.Rd
tests/testthat/test-data.R

This is a small pull request that closes #1625.
This PR provides the argument `ascii` to `use_data()`. By default it is set to FALSE, when true ASCII representations of the passed in objects are written. Documentation has been updated to include the new argument.

add ASCII argument to use_data

---

R/readme.R
man/use_readme_rmd.Rd

I have run into a couple of times where I need to undo the git hook* and I don't know how to, so this is a brief note about the pre-commit hook in use_readme_rmd() behavior.
\* e.g., the README.Rmd reads in a file for demonstration. The file changes and README.Rmd is knitted to give README.md. README.Rmd is unchanged, README.md is changed, but README.md cannot be committed because the unchanged README.Rmd is not also staged.

add note to use_readme_rmd() docs

---

R/logo.R

Asking if over writing the file is allowed is performed in the first part of `use_logo()`. If approved, the destination should be overwritten.
Current error: 
```
❯❯ usethis::use_logo("logo/shinytest2.svg")
✔ Setting active project to '/Users/barret/Documents/git/rstudio/shinytest/shinytest2.nosync'
Overwrite pre-existing file 'man/figures/logo.svg'?
1: No
2: Absolutely not
3: Yeah
Selection: 3
Error: [EEXIST] Failed to copy 'logo/shinytest2.svg' to '/Users/barret/Documents/git/rstudio/shinytest/shinytest2.nosync/man/figures/logo.svg': file already exists
```
With PR (working):
```
❯❯ usethis::use_logo("logo/shinytest2.svg")
✔ Setting active project to '/Users/barret/Documents/git/rstudio/shinytest/shinytest2.nosync'
Overwrite pre-existing file 'man/figures/logo.svg'?
1: For sure
2: …
```

Overwrite file on `file_copy()`

---

R/pkgdown.R
R/proj.R
tests/testthat/_snaps/proj.md
tests/testthat/test-proj.R

`proj_path()` always returns paths with the project root prepended to it, even if the path is already absolute. This is less of a big deal with using `proj_path()` directly (since it's obviously intended to do that) and more when we use it internally to process paths, as in `use_github_file()`.  (I recently tried to save a file using an absolute path interactively, which did not work)
This PR modifies `proj_path()` to ~~respect~~ reject absolute paths

Error with abs paths in `proj_path()`

---

R/helpers.R
R/package.R
man/use_package.Rd
man/use_pkgdown.Rd
tests/testthat/_snaps/package.md
tests/testthat/test-package.R

Related to #1619, this PR smooths out the process of using `use_package()` to bump the R version dependency:
* Add an example to docs
* Don't advise against using `Depends` for `R`
* Allow `min_version = TRUE` to detect current R version 
* Require that `min_version` is set and that `type` is `Depends`

Improve `use_package("R", ...)` experience and add example

---

R/r.R
R/rcpp.R
tests/testthat/_snaps/r.md
tests/testthat/_snaps/rcpp.md
tests/testthat/test-r.R
tests/testthat/test-rcpp.R

Currently, `use_r("")` creates `R/.R`, which I don't think is ever what someone wants. This PR adds a check for `use_r()` and friends to make sure the file actually has a name.

Fix `use_r("")` and similar

---

NEWS.md
R/create.R
R/description.R
R/proj.R
tests/testthat/test-create.R

Closes #1643
We discourage nested projects, but it is possible, mostly for developers. So we should at least behave correctly in this code path.
Previously, a nested project would put the name of the parent project in DESCRIPTION, which causes a variety of downstream problems. The `.Rproj` file gets the wrong name. Every call to `project_name()` returns the wrong name.
Also, when `proj_set(force = TRUE)`, we should bypass the initial early return if we discover that we are already in a project. The whole point of `force = TRUE` is to do exactly as we are told. This was causing the active project to be still be set to the parent, when trying to work with a nested project.

Rationalize nested projects

---

man/figures/lifecycle-archived.svg
man/figures/lifecycle-defunct.svg
man/figures/lifecycle-deprecated.svg
man/figures/lifecycle-experimental.svg
man/figures/lifecycle-maturing.svg
man/figures/lifecycle-questioning.svg
man/figures/lifecycle-soft-deprecated.svg
man/figures/lifecycle-stable.svg
man/figures/lifecycle-superseded.svg

Add `aria-label` and semantic title to lifecycle-badge SVGs for accessibility.
Part of https://github.com/r-lib/usethis/issues/1554 and related to https://github.com/r-lib/lifecycle/issues/117.

Add aria-labels and titles to lifecycle badges.

---

vignettes/articles/usethis-setup.Rmd

Per discussion on R packages 2e https://github.com/hadley/r-pkgs/issues/854

remove usethis.protocol  = "ssh" from example .Rprofile options

---

NEWS.md
R/vignette.R
tests/testthat/test-vignette.R

Motivated by experiments made while updating R Packages
Basically I found it confusing that knitr was added to `DESCRIPTION` early on and then ... later ... rmarkdown was added.
I can't think of any reason why we had it this way and looking through git blame didn't shed any light either.
This seems more obvious and obviously correct to me.
---
BEFORE
``` r
> use_vignette("my-vignette")
✔ Adding 'knitr' to Suggests field in DESCRIPTION
✔ Setting VignetteBuilder field in DESCRIPTION to 'knitr'
✔ Adding 'inst/doc' to '.gitignore'
✔ Creating 'vignettes/'
✔ Adding '*.html', '*.R' to 'vignettes/.gitignore'
✔ Adding 'rmarkdown' to Suggests field in DESCRIPTION
✔ Writing 'vignettes/my-vignette.Rmd'
• Modify 'vignettes/my-vignette.Rmd'
```
AFTER
``` r
> use_vignette("my-vignette")
✔ Adding 'knitr' …
```

Refactor `use_vignette()`

---

R/create.R
R/git.R
man/create_from_github.Rd
man/create_package.Rd
man/git_sitrep.Rd
man/use_git_hook.Rd

We're reading all of the usethis docs "cover to cover" in a new "book club" at R4DS. These are some tweaks I noticed while reading the Configuration and Git & GitHub sections. I didn't re-document, since I *think* that happens automatically.
I removed the git_vaccinate() reference in git_sitrep help, because I *think* it's left over from them previously living in the same doc.

Documentation readability edits.

---

inst/templates/package-README
inst/templates/project-README
tests/testthat/_snaps/readme.md

Inspired by R Package 2e revision. We don't actually wire this up in our own repos, so I think we should get it out of the templates. Streamlining content for the majority is always good. The GHA/CI keeners are always able to use the GHA example for rendering an `.Rmd`, if they are so motivated.

Don't mention GHA for README-rendering in README templates

---

NEWS.md
R/r.R
R/rcpp.R
R/utils.R
man/use_r.Rd
man/use_rcpp.Rd
tests/testthat/_snaps/r.md
tests/testthat/_snaps/rcpp.md
tests/testthat/test-r.R
tests/testthat/test-rcpp.R
tests/testthat/test-utils.R

* Make it much broader so it now works with any file in `R/`, `src/` or `tests/testthat`. Fixes #1566
* This new foundation made it possible to make `use_c()` and `use_rcpp()` (and friends) to work the same way as `use_r()`/use_test()`.
* Since I was in here I fixed #1690.
* I also refactored the code to make it easier to test.
* I switched the errors I touch to use `cli::cli_abort()` so the messaging can point to the correct user facing function.
* I generally refactored the error handling so it happens in one central location.

Refactor get_active_file()

---

NEWS.md
R/git.R
R/github_token.R
R/utils-git.R
tests/manual/manual-git-sitrep.R

fix #1706
While `git_sitrep()` was still loaded into my brain, I thought to take a swing at this. Given that `git_sitrep()` can be run in bits-and-pieces, I thought the feedback should be proximate to where the error was happening.
Following @jonthegeek's reprex:
``` r
dat <- gert::git_config_global()
if ("user.email" %in% dat$name) {
old_email <- dat[dat$name == "user.email",]$value
usethis::use_git_config(user.email = NULL)
}
usethis::git_sitrep(scope = "user")
#> 
#> ── Git global (user)
#> • Name: 'Ian Lyttle'
#> • Email: <unset>
#> • Global (user-level) gitignore file: '~/.gitignore'
#> • Vaccinated: TRUE
#> ℹ Defaulting to 'https' Git protocol
#> • Default Git protocol: 'https'
#> • Default initial branch name: 'main'
#> 
#> 
#> ── GitHub user 
#> 
#> • Default GitHub host: …
```

handle case where user-email not set

---

R/pr.R
man/pull-requests.Rd

Attempt to clarify pr_fetch() vs pr_resume()

---

NEWS.md
R/latest-dependencies.R
man/use_latest_dependencies.Rd
tests/testthat/test-latest-dependencies.R

Fixes #1749
Also a nice opportunity to use the new `proj_deps()` helper in the tests.

Don't update suggested dependencies

---

R/utils.R

These have been soft deprecated for awhile, but in dev rlang they have been bumped from `deprecate_soft()` to `deprecate_warn()` https://github.com/r-lib/rlang/commit/35e87908418619f70917e191a2d9721c709527d0
So now users will see the deprecation warnings, which appear in `pr_push()`:
```r
> usethis::pr_push()
✔ Setting active project to '/Users/davis/Desktop/r/packages/dplyr'
Which repo do you want to push to? 
1: DavisVaughan/dplyr = 'origin' (external PR)
2: tidyverse/dplyr = 'upstream' (internal PR)
Selection: 1
✔ Pushing local 'fix/rlang-deprecations' branch to 'origin' remote.
• Create PR at link given below
✔ Opening URL 'https://github.com/DavisVaughan/dplyr/compare/fix/rlang-deprecations'
Warning messages:
1: `as_integer()` is deprecated as of rlang 0.4.0
Please use …
```

Avoid deprecated rlang coercion helpers

---

R/release.R
tests/testthat/_snaps/release.md

This came from a discussion @hadley and I had today, while releasing httr and working on the CRAN release chapter of R Packages 2e.
We feel like we get so much value from our ongoing checks via GitHub Actions, that the last-minute pre-release r-hub checks don't really add anything, in most situations. Also, if there is some undiscovered problem, it now shows up in an automated incoming CRAN check and doesn't bother any humans. Then r-hub becomes relevant as part of the troubleshooting toolkit.
Something I considered but did not implement:
We could check if the package has `.github/workflows/R-CMD-check.yaml` and, if it **does not** have such a file, include the checklist items I'm deleting here.

Remove rhub from release checklist

---

R/citation.R
inst/templates/citation-template.R
tests/testthat/test-citation.R

This PR:
- replaces the scaffolding for CITATION using `bibentry`
- adds a test
As per #1695 the `textVersion` field is not needed unless specific LaTeX formatting (e.g, mathematical symbols, accented characters) is required. The `citation()` print method uses the fields in `bibentry()` to automatically generate the "To cite package {packagename} in publications use:..." text. It infers the package name, so there is no need to populate it when copying the template.
Closes #1695

Use bibentry in citation template

---

R/tidy-upkeep.R

During spring cleaning I came across a package that didn't have a tests directory so `fs::dir_ls()` fails, stopping the checklist creation.

Make `lowercase_r()` robust to missing directories for `use_tidy_upkeep_issue()`

---

NEWS.md
R/version.R
man/use_version.Rd

Completes the intent of #1385 and #1746
Without this PR, this item of the release checklist fails:
https://github.com/r-lib/usethis/blob/50074f88a744affc72e05865b7480c704bac502b/R/release.R#L138

Add the `push` argument to `use_dev_version()`

---

R/use-standalone.R
R/utils.R
man/use_standalone.Rd
tests/testthat/_snaps/use-standalone.md
tests/testthat/test-use-standalone.R

This will pick up the new `imports:` field added in https://github.com/r-lib/rlang/pull/1589 and ensure all dependencies are with sufficient versions are included in `Imports`.

Add support for `imports` field in standalone files

---

R/version.R

Currently with dev usethis I see this with `use_version()` with no arguments
```r
> usethis::use_version()
Current version is 0.5.2.9000.
What should the new version be? (0 to exit) 
1: major --> 1.0.0
2: minor --> 0.6.0
3: patch --> 0.5.3
4:   dev --> 0.5.2.9001
Selection: 2
✔ Setting Version field in DESCRIPTION to '0.6.0'
Error in if (names(new_ver) == "dev") { : argument is of length zero
```
This is due to this change in `choose_version()` https://github.com/r-lib/usethis/pull/1784
Particularly, this line, which now uses `[[` to subset `versions` (which is reasonable because there is only 1 `choice`).
https://github.com/r-lib/usethis/blob/a336c671b79df60ca287a6ca60eeab5e9b0092be/R/version.R#L121
It is problematic here because `[[` drops the names of `versions`, and we actually need …

Retain names of `versions` when subsetting

---

DESCRIPTION
R/browse.R
R/course.R
R/data.R
R/git-default-branch.R
R/git.R
R/github-actions.R
R/github-pages.R
R/helpers.R
R/import-standalone-obj-type.R
R/import-standalone-types-check.R
R/tidyverse.R
R/tutorial.R
R/ui.R
R/use_github_file.R
R/utils-git.R
R/utils-github.R
R/utils-rematch2.R
R/utils.R
R/vignette.R
R/write.R
tests/testthat/_snaps/course.md
tests/testthat/_snaps/tutorial.md
tests/testthat/test-course.R
tests/testthat/test-tutorial.R

Closes #1803 
Replaces the bespoke type-checking with with the checkers from `use_standalone("r-lib/rlang", "types-check")`.
Most are pretty straightforward, but I did rearrange some to try to simplify the logic - particularly in `use_github_action()`.
I used `check_name()` a lot over `check_string()` as it disallows `""`, which I think is warranted, though the previous checks would have allowed it.
I created a `maybe_name()` wrapper around `check_name(x, allow_null = TRUE)` as there are lots of arguments with NULL as a default value.
This PR replaces #1798, which I closed then rebased this branch as `main` had got quite far ahead.

Implement type checkers from rlang standalone-types-check.R

---

R/logo.R
R/use_standalone.R
README.Rmd
README.md

Closes #1804 
* When the logo is not a link to the pkgdown site, alt text is simply "", as the logo is decorative.
* When the logo is also a link to the pkgdown site, the alt text describes the link destination as per accessibility standards (https://www.w3.org/WAI/WCAG21/Techniques/html/H30.html)

`use_logo()` adds appropriate alt-text in README

---

R/use_standalone.R
tests/testthat/test-use_standalone.R

- Allow passing in prefixed standalone file names like `aaa-standalone-foo`
- While I was in there I added type-checking for `file` using the rlang standalone file.

Support prefixed standalone files

---

R/description.R
R/github.R
R/license.R
R/pkgdown.R
R/proj-desc.R
R/roxygen.R
R/spelling.R
R/test.R
R/version.R
R/vignette.R
tests/testthat/_snaps/proj-desc.md
tests/testthat/test-browse.R
tests/testthat/test-description.R
tests/testthat/test-news.R
tests/testthat/test-proj-desc.R
tests/testthat/test-version.R
tests/testthat/test-vignette.R

`use_description_field()` and `proj_desc_field_append()` do very similar things. This combines them into one function with arguments `overwrite` and `append` to allow the existing behaviour of the original two functions:
* `proj_desc_field_append()` -> `proj_desc_field_update()`
* remove `use_description_field()`
* add overwrite and append arguments to `proj_desc_field_update()`
* replace use of `use_description_field()` and `proj_desc_field_append()` with `proj_desc_field_update()`, setting overwrite and append arguments as appropriate
* update tests
NB: There will be merge conflicts after #1834 is merged.

Rationalize use_description_field() & proj_desc_field_append()

---

NEWS.md
R/description.R
R/github.R
tests/testthat/_snaps/github.md
tests/testthat/test-github.R

Closes #1805.
Allows appending of the GitHub repo url to existing urls in the `URL` `DESCRIPTION` field. Appending is the default behaviour (i.e., when `overwrite = FALSE`). When `overwrite = TRUE` it will overwrite the old value with the GitHub repo url. 
This is slightly different behaviour than before as there is now no option to leave the `URL` field as-is: it will either be replaced, or appended to. I think this is ok, since why would you use the function if you didn't want to update the field? The alternative would be to allow three options: append, overwrite, or leave as is...

Allow appending urls in `use_github_links()`

---

R/proj-desc.R
R/test.R
tests/testthat/_snaps/proj-desc.md
tests/testthat/test-proj-desc.R

Coming from https://github.com/r-lib/desc/issues/117#issuecomment-1554499421
I understand why this doesn't happen in usethis test where testthat edition field is already set by `create_local_package()`; after digging a bit I see that prior to https://github.com/r-lib/usethis/commit/747931bdee400be9969b7ab75af390c05ff2e7a9 there was `as.character()`. Now I am at peace, having the whole story :jigsaw: :relieved: 
@krlmlr

fix: make use_testthat() work for brand-new package

---

R/release.R
tests/testthat/_snaps/release.md
tests/testthat/test-proj-desc.R

Closes #1761. 
As pointed out by @DavisVaughan in the linked issue, there is no perfect place for this bullet in the checklist. I made the assumption that the user won't be pushing the released version to GitHub prior to CRAN acceptance, so I moved the bullet to after CRAN acceptance and before `use_github_release()`, which will push to GitHub and thus build the released version of the pkgdown site, with the link to the blog post in the pkgdown news. The link will 404 until the post is published but that shouldn't usually be a long delay.

Move up "add link to blog post" release bullet

---

R/release.R
tests/testthat/test-release.R

Fixes #1857.
This:
- Bails and returns `NULL` if offline.
- Passes `default_cran_version()` to the `repos` argument of `available.packages()` (this seemed more straightforward than setting local options). 
- `default_cran_version()` is borrowed from [pak](https://github.com/r-lib/pak/blob/168ab5d58fc244e5084c2800c87b8a574d66c3ba/R/default-cran-mirror.R#L4), however I set the fallback mirror to `cloud.r-project.org` rather than `cran.rstudio.com`, which seems more canonical - but I'm happy to be re-educated. 
- I modified `default_cran_version()` from pak to respect the users' other repos and append CRAN rather than replace the entire repos option with just CRAN. (As implemented in pak it only returns a CRAN repo, even if the user had other repos set in their `repos` option).
- The call to …

Ensure `cran_version()` does not fail when no internet or CRAN mirror is unset

---

R/write.R
tests/testthat/_snaps/write.md
tests/testthat/test-write.R

Closes #1859
`ui_path()` already takes care of making the path relative to the project.

Use ui_path() as it was designed to be used

---

R/r.R
tests/testthat/test-r.R

Closes #1863
Please see #1863 for a description of the issue that this PR is aiming to address.

Make compute_name() work when `ext` is not "R"

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
tests/testthat/test-author.R
tests/testthat/test-tidyverse.R

Always compare a version to character, not double

---

R/release.R
tests/testthat/_snaps/release.md

I assume the intent here is to get the blog post into the newly built site, but I found the order action a bit confusing, especially given that I like to be absolutely sure I'm getting the right url by copying it from the live site.

Tweak blog post action order

---

R/cran.R

The template was changed two years ago to no longer use `rversion`, so no need to provide it.

remove unused parameter in use_cran_comments()

---

.github/SUPPORT.md
inst/templates/tidy-support.md

As there's a shift away from [using descriptions of mental illness as generic intensifiers](https://www.npr.org/2019/07/08/739643765/why-people-are-arguing-to-stop-using-the-words-crazy-and-insane), and usethis provides the template for many SUPPORT.md files, I think it might be nice to use more inclusive language in the default SUPPORT.md template. This PR changes the word "insane" to "incredible" in both the tidy-support template and in the SUPPORT.md generated from this file in this repo.

Shift tidy support template (and SUPPORT.md) to use inclusive language

---

R/documentation.R
man/use_package_doc.Rd

Add `use_package_doc()` details for package and function by the same name

---

tests/testthat/test-cpp11.R
tests/testthat/test-github-actions.R
tests/testthat/test-helpers.R
tests/testthat/test-use_standalone.R

This is just to remove unrelated stuff from #1928

Minor test lints

---

.github/workflows/R-CMD-check.yaml

The newest magick can't be installed for R 3.6 on Windows.
Following advice given here: https://github.com/r-lib/actions/tree/v2/setup-r-dependencies#ignoring-optional-dependencies-that-need-a-newer-r-version

Don't try to install magick on R 3.6

---

NEWS.md
R/news.R
tests/testthat/test-news.R

tolerate empty lines at start of news file

---

R/github.R

This changes `check_no_github_repo()` to check the name of the response from the GitHub API against the provided spec (user/repo) - If they are different it assumes it's a redirect and then proceeds and allows repo creation. It retains the behaviour where if request to the GitHub API returns a 404 it similarly passes and allows the creation of the new repo.
Unfortunately the response returned from the GitHub API doesn't appear to explicitly say it's been redirected (i.e., it's a 200 HTTP code, not a 301).
Fixes #1893.
I didn't add any tests - though could add to the manual tests if you like?

`use_github()` - allow repo creation when repo is a redirect

---

R/create.R
R/description.R
man/use_description.Rd

Remove self-reference from use_description() documentation

---

NEWS.md
R/github.R
R/release.R
R/upkeep.R
R/utils-github.R
tests/testthat/test-github.R
tests/testthat/test-release.R
tests/testthat/test-utils-github.R

Addresses #2023 
We have to be careful around calling functions inside the `(release|upkeep)_checklist()` helpers that need to know which GitHub repo we're targetting. We're at risk of asking the user to choose the repo over and over again, with no context, if the user happens to have a fork of the source repo. We already _know_ the target repo at this point, so we propagate that info now.

Stop repeating "which repo?" question in use_release_issue()

---

R/package.R
man/use_package.Rd

On several occasions now I have tried to add a minimum package version using a `double` like so:
```r
usethis::use_package("my_package", min_version = 1.1.0)
```
Each time I get an error, as I incorrectly guessed that `min_version` would require a numeric type. While I think the error message is helpful enough (`Error: unexpected numeric contstant in "usethis...`), I think the documentation could be improved.
Currently, it is only clear that `min_version` should be a character vector when looking at the examples. The parameter documentation is not clear in and of itself.

Indicate argument type

---

R/pr.R

Sometimes, if you reopen a project later, you may want to be able to jump back to the PR URL

Add PR link to pr_finish

---

R/github-actions.R

it would be a way to update the URL like we can when updating check action.
Workflow (After deleting temporarily from usethis README.Rmd)
Doesn't prompt if the badge already exist.
Should it check for `codecov.yml`?

Add badge when updating coverage action

---

R/rename-files.R
man/rename_files.Rd
tests/testthat/test-rename-files.R

Check for uncommitted changes before renaming files, and only remove `.R` file extensions in `old` and `new`.
Fixes #1969.
I *think* this is the least-surprising approach to take. It's probably best to just not use `.` in filenames, but this will stop things from breaking in confusing ways when people do.

Dots in rename

---

R/git.R

Fixes #2034 
If the default git communication protocol isn't set, `git_protocol()` sets a default *and* messages the user about the chosen default. That message looks confusing in the output bullets for `git_sitrep()`. This PR suppresses that message.
Putting `suppressMessages()` directly in the `kv_line()` call didn't seem to work (maybe something about the environment?), so I split it into two steps. 
These chunks were useful for testing changes since I had some of these options set in my user-level .Rprofile:
```r
devtools::load_all()
options("usethis.protocol" = NULL)
git_protocol()
options("usethis.protocol" = NULL)
git_sitrep()
```

suppress git_protocol message in git_sitrep

---

NEWS.md
R/data.R
man/use_data.Rd
tests/testthat/test-data.R

Fixes #1966  - The grand sum of this update is one character (plus a news bullet) Note that this change did not break anything in any test (should a test be added?)

Bump default serialization version in use_data() to 3

---

NEWS.md
R/helpers.R
tests/testthat/_snaps/helpers.md
tests/testthat/test-helpers.R

Let `use_package()` decrement a package dependency.

---

R/data.R
R/proj-desc.R
R/use_standalone.R
R/utils-git.R
R/utils-github.R
tests/manual/manual-use-github.R
tests/testthat/test-proj.R
tests/testthat/test-utils-github.R

Hello, I'm building a new package to find and automatically fix lints in R code: [`flint`](https://flint.etiennebacher.com/).
I'm using real-life, large packages to check its performance (both in speed and in correctness of the fixes) and `usethis` is one of them. Since I already test on this, there's almost no additional cost for me in proposing those changes.
FYI, those changes were generated with `flint::fix_package()`.
Most changes are trivial:
- replace `any(is.na())` by `anyNA()`
- replace `expect_identical(x, NULL)` by `expect_null(x)`
etc.
There's also likely a bug fix: `length(old > 0)` is replaced by `length(old) > 0`.
`flint` is quite new and linter rules are necessarily a bit opinionated (but I follow `lintr` most of the time), so some of those changes might not be to your …

Fix some lints

---

R/ui-legacy.R

Replaces "(LINK TO COME)" text in ui-legacy.R roxygen.
No existing issue that I could find.

Adds link to cli vignette on transition from ui_*()

---

R/pr.R

I realised that we're checking whether or not the host is online further down, so we might as well use that a little earlier to give a more informative message.

Specifically handle offline case in `pr_init()`

---

tests/testthat/_snaps/use_import_from.md
tests/testthat/test-use_import_from.R

Closes #2079 
waldo previously imported tibble so switch to a package that will always be installed with usethis.
This fixes the failure on CRAN.

Use lifecycle instead of tibble

---

NEWS.md
R/vignette.R
inst/templates/article.qmd
inst/templates/vignette.qmd
man/use_vignette.Rd
tests/testthat/_snaps/vignette.md
tests/testthat/test-vignette.R

Assist with Quarto vignettes and articles

---

R/directory.R
tests/testthat/test-directory.R

Fixes #2069 
@gaborcsardi I tagged you for fs experise. Am I failing to take advantage of anything in fs? Does fs have the equivalent of what `readlink` is doing? Does fs need a function worthy of the name `link_target()`? Hmm, I guess that's just what `path_real()` is?
This guards specifically against a (somewhat peculiar?) situation on macOS.
First, I have this in `.Renviron` to get nicer looking temp file paths. I think this is pretty common among R users or R power users:
```
TMPDIR=/tmp
```
`/tmp` is actually a symlink on macOS, but it's a *relative* symlink:
```
~/rrr/usethis % ls -l /tmp
lrwxr-xr-x@ 1 root  wheel  11 May  3 22:39 /tmp -> private/tmp
```
So it has to be interpreted relative to this directory it lives in, namely `/`.
If you use `readlink` instead, you get the full …

Stop calling `link_path()` and let `is_dir()` do its thing

---

R/test.R
tests/testthat/_snaps/test.md
tests/testthat/test-test.R

So the tests don't fail if you happen to be working on the development version of testthat.

Introduce mockable `testthat_version()`

---

R/release.R
tests/testthat/_snaps/release.md

IMO if you're worried you need to run revdeps it's not a patch release, and the CRAN checks are now automated enough it's not a big deal if we miss something.

Drop revdep check from patch release

---

NEWS.md
R/pr.R
R/utils-ui.R
tests/testthat/test-utils-ui.R

This was meant to be a PR into #2169, but I forgot to set that when I created this PR, so I'm closing that and moving here.
Added a simple helper to escape curly braces for glue (`ui_escape_glue()` in `utils-ui.R`), then applied it in the relevant `pr_*()` functions. I used Positron Assistant (with Claude) and Google Gemini (using my personal setup) on this to test Positron Assistant, then revised their fixes significantly. 
`pr_pause()` then `pr_resume()` shows the title of this PR properly, as does `pr_fetch()` (with no number). `pr_fetch(2171)` also shows this title properly.
Fixes #2107.

Add a {test} for `ui_escape_glue()` helper
